/* ═══════════════════════════════════════════════════════════════════════════
   THE DARK ORCHARD — render.js

   One full-screen fragment shader. There is no mesh, no vertex buffer and no
   culling here, because the thing the room needs is not a picture of the
   orchard: it is the PATH LENGTH from the bat's mouth to every solid, and a
   sphere-traced ray from the eye hands that back for free. The eye IS the
   mouth, so the marched distance t is the one-way path and 2t/c is the delay.

   So the picture is drawn by the same number the sound is: nothing on the
   screen is lit unless an echo has had time to come back from it.

   Pipeline: march (HDR, RGBA16F) -> bright pass at 1/4 -> separable blur ->
   filmic composite. The scene arrives as uniforms straight out of orchard.mjs
   CAPS; the distance function itself is GENERATED by orchard.mjs sdfGLSL() so
   the shader and the Node twin cannot be looking at two different orchards.
   ═══════════════════════════════════════════════════════════════════════════ */

const DO = {};

DO.VS = `#version 300 es
void main(){
  vec2 p = vec2((gl_VertexID << 1) & 2, gl_VertexID & 2);
  gl_Position = vec4(p * 2.0 - 1.0, 0.0, 1.0);
}`;

DO.marchFS = (sdf, beam, nCap, nGroup) => `#version 300 es
precision highp float;
#define NCAP ${nCap}
#define NGROUP ${nGroup}
#define NCH 8
#define NLUT 24
#define NPROBE 16

uniform vec4  uCapA[NCAP];       // xyz = a, w = radius
uniform vec4  uCapB[NCAP];       // xyz = b, w = material
uniform vec4  uGroup[NGROUP];    // xyz = centre, w = bounding radius
uniform vec4  uRange[NGROUP];    // x = from, y = to
uniform vec3  uMoth;

uniform vec3  uEye, uFwd, uRight, uUp;
uniform vec2  uRes;
uniform float uTanHalf;

/* one chirp per vec4: (screen seconds since it left, half-width of its range
   profile in screen seconds, relative amplitude, unused) */
uniform vec4  uCh[NCH];
uniform int   uNCh;

uniform float uInvHalfPath;      // screen seconds of delay per metre of range
uniform float uAlpha2;           // 2 * alpha(f_mid) in nepers per metre
uniform float uKa;               // 2 pi f a / c, the beam's piston parameter
uniform float uTau;              // visual persistence, screen seconds
uniform float uGain, uRing;
uniform vec4  uRefl[2];          // six materials, packed
uniform vec4  uCent[NLUT/4];     // returned spectral centroid vs range, Hz
uniform float uCentMax;          // the range the LUT spans
uniform float uMothFlick;        // wingbeat phase term, already in screen time
uniform float uProbe;            // >0.5: write the marched distance instead
uniform vec4  uProbeDir[NPROBE];

out vec4 frag;

${sdf}
${beam}

vec3 sceneNormal(vec3 p){
  const vec2 k = vec2(1.0, -1.0);
  const float e = 0.0016;
  return normalize(
      k.xyy * sdScene(p + k.xyy*e).x + k.yyx * sdScene(p + k.yyx*e).x
    + k.yxy * sdScene(p + k.yxy*e).x + k.xxx * sdScene(p + k.xxx*e).x);
}

float lut(int i){ return uCent[i >> 2][i & 3]; }
float mat6(int i){ return i < 4 ? uRefl[0][i] : uRefl[1][i - 4]; }

/* the pitch of what comes back, from a 24-entry table of the exact integral */
float centroidAt(float d){
  float u = clamp(d / uCentMax, 0.0, 1.0) * float(NLUT - 1);
  int i = int(floor(u));
  int j = min(i + 1, NLUT - 1);
  return mix(lut(i), lut(j), u - float(i));
}

/* a returning echo's colour IS its pitch: the air eats the top of the sweep
   first, so far things come back low and warm and near things come back
   bright and cold. Nothing else in this room carries colour. */
vec3 pitchColour(float fHz){
  float f = fHz * 1e-3;
  vec3 a = vec3(1.00, 0.36, 0.13);   // 45 kHz, ember  — all that is left after 8 m of air
  vec3 b = vec3(1.00, 0.72, 0.33);   // 49
  vec3 c = vec3(0.97, 0.95, 0.88);   // 53
  vec3 d = vec3(0.62, 0.81, 1.00);   // 58, cold silver — the whole sweep, at arm's length
  if (f < 49.0) return mix(a, b, smoothstep(45.0, 49.0, f));
  if (f < 53.0) return mix(b, c, smoothstep(49.0, 53.0, f));
  return mix(c, d, smoothstep(53.0, 58.0, f));
}

void main(){
  vec2 uv = (gl_FragCoord.xy - 0.5*uRes) / uRes.y;
  vec3 rd = normalize(uFwd + uRight * (uv.x * uTanHalf * 2.0) + uUp * (uv.y * uTanHalf * 2.0));
  if (uProbe > 0.5) rd = normalize(uProbeDir[int(gl_FragCoord.x)].xyz);

  vec3 hitv = marchScene(uEye, rd);   /* generated by orchard.mjs, same five numbers as march() */
  float t = hitv.x;
  float m = hitv.y;
  bool hit = hitv.z > 0.5;

  if (uProbe > 0.5){ frag = vec4(hit ? t : -1.0, m, 0.0, 1.0); return; }

  if (!hit){ frag = vec4(0.0, 0.0, 0.0, 1.0); return; }

  vec3 p = uEye + rd * t;
  vec3 n = sceneNormal(p);
  float inc = max(0.04, -dot(rd, n));
  float ct  = clamp(dot(rd, uFwd), 0.0, 1.0);
  float bm  = pistonGain(ct, uKa) * earGain(ct);   /* out through the mouth, back through the ears */

  int mi = int(m + 0.5);
  float refl = mat6(mi);

  /* chalk survey rings on the grass, one metre apart, painted round the peg
     at the origin. They are not light: they are a patch of the ground that
     sends more back, so you can read the sweep off them. */
  if (mi == 0 && uRing > 0.0){
    float r = length(p.xz);
    float band = 1.0 - smoothstep(0.0, 0.045, abs(fract(r + 0.5) - 0.5));
    refl *= 1.0 + uRing * 1.9 * band;
  }

  /* one echo's strength: out through the beam, onto the patch, back again */
  float strength = bm * refl * inc * exp(-uAlpha2 * t) / (t * t);
  if (mi == 5) strength *= 1.0 + 0.55 * cos(uMothFlick);

  /* when it gets here, and how long the eye is allowed to keep it */
  float arrive = t * uInvHalfPath;
  float e = 0.0;
  for (int k = 0; k < NCH; k++){
    if (k >= uNCh) break;
    float u = uCh[k].x - arrive;
    float w = max(uCh[k].y, 0.004);
    float rise = smoothstep(-w, w, u);
    float dec  = exp(-max(u - w, 0.0) / uTau);
    e += uCh[k].z * rise * dec;
  }

  float v = e * strength * uGain;
  vec3 col = pitchColour(centroidAt(t)) * v;
  frag = vec4(col, 1.0);
}`;

DO.brightFS = `#version 300 es
precision highp float;
uniform sampler2D uSrc;
uniform vec2 uSrcTexel;
uniform float uThresh;
out vec4 frag;
void main(){
  vec2 uv = gl_FragCoord.xy * uSrcTexel * 4.0;
  vec3 s = vec3(0.0);
  for (int j = -1; j <= 1; j++) for (int i = -1; i <= 1; i++)
    s += texture(uSrc, uv + vec2(float(i), float(j)) * uSrcTexel * 2.0).rgb;
  s /= 9.0;
  float l = max(max(s.r, s.g), s.b);
  frag = vec4(s * max(0.0, l - uThresh) / max(l, 1e-4), 1.0);
}`;

DO.blurFS = `#version 300 es
precision highp float;
uniform sampler2D uSrc;
uniform vec2 uTexel;
uniform vec2 uDir;
out vec4 frag;
void main(){
  vec2 uv = gl_FragCoord.xy * uTexel;
  vec3 s = texture(uSrc, uv).rgb * 0.2270270270;
  vec2 o1 = uDir * uTexel * 1.3846153846;
  vec2 o2 = uDir * uTexel * 3.2307692308;
  s += (texture(uSrc, uv + o1).rgb + texture(uSrc, uv - o1).rgb) * 0.3162162162;
  s += (texture(uSrc, uv + o2).rgb + texture(uSrc, uv - o2).rgb) * 0.0702702703;
  frag = vec4(s, 1.0);
}`;

DO.compositeFS = `#version 300 es
precision highp float;
uniform sampler2D uScene, uBloom;
uniform vec2 uSceneTexel, uBloomTexel;
uniform float uBloomAmt, uVig;
out vec4 frag;

/* ACES-ish, so a bright near return rolls off instead of clipping to white */
vec3 tonemap(vec3 x){
  const float a = 2.51, b = 0.03, c = 2.43, d = 0.59, e = 0.14;
  return clamp((x*(a*x+b))/(x*(c*x+d)+e), 0.0, 1.0);
}
void main(){
  vec3 s = texture(uScene, gl_FragCoord.xy * uSceneTexel).rgb;
  vec3 b = texture(uBloom, gl_FragCoord.xy * uBloomTexel).rgb;
  vec3 c = s + b * uBloomAmt;
  vec2 q = gl_FragCoord.xy * uSceneTexel - 0.5;
  c *= 1.0 - uVig * dot(q, q) * 1.6;
  c = tonemap(max(c, 0.0));
  frag = vec4(pow(c, vec3(1.0/2.2)), 1.0);
}`;

/* ─────────────────────────────────────────────────────────────────────── */

function compile(gl, type, src) {
  const s = gl.createShader(type);
  gl.shaderSource(s, src); gl.compileShader(s);
  if (!gl.getShaderParameter(s, gl.COMPILE_STATUS)) {
    const log = gl.getShaderInfoLog(s);
    const numbered = src.split('\n').map((l, i) => (i + 1) + ': ' + l).join('\n');
    throw new Error('shader: ' + log + '\n' + numbered.slice(0, 2600));
  }
  return s;
}
function program(gl, vs, fs) {
  const p = gl.createProgram();
  gl.attachShader(p, compile(gl, gl.VERTEX_SHADER, vs));
  gl.attachShader(p, compile(gl, gl.FRAGMENT_SHADER, fs));
  gl.linkProgram(p);
  if (!gl.getProgramParameter(p, gl.LINK_STATUS)) throw new Error('link: ' + gl.getProgramInfoLog(p));
  return p;
}
function uniforms(gl, p) {
  const u = {};
  const n = gl.getProgramParameter(p, gl.ACTIVE_UNIFORMS);
  for (let i = 0; i < n; i++) {
    const info = gl.getActiveUniform(p, i);
    const name = info.name.replace(/\[0\]$/, '');
    u[name] = gl.getUniformLocation(p, info.name);
  }
  return u;
}

DO.Renderer = class {
  constructor(canvas, caps, groups, refl, sdfSrc, beamSrc) {
    const gl = canvas.getContext('webgl2', { antialias: false, alpha: false, depth: false, powerPreference: 'high-performance' });
    if (!gl) throw new Error('no WebGL2');
    if (!gl.getExtension('EXT_color_buffer_float')) throw new Error('no float render targets');
    this.gl = gl; this.canvas = canvas;
    this.nCap = caps.length; this.nGroup = groups.length;
    this.refl = new Float32Array(refl);

    this.pMarch = program(gl, DO.VS, DO.marchFS(sdfSrc, beamSrc, this.nCap, this.nGroup));
    this.pBright = program(gl, DO.VS, DO.brightFS);
    this.pBlur = program(gl, DO.VS, DO.blurFS);
    this.pComp = program(gl, DO.VS, DO.compositeFS);
    this.uMarch = uniforms(gl, this.pMarch);
    this.uBright = uniforms(gl, this.pBright);
    this.uBlur = uniforms(gl, this.pBlur);
    this.uComp = uniforms(gl, this.pComp);

    this.vao = gl.createVertexArray();

    /* the scene, packed once — setCaps() re-uploads when a post moves */
    this.capA = new Float32Array(this.nCap * 4);
    this.capB = new Float32Array(this.nCap * 4);
    this.grp = new Float32Array(this.nGroup * 4);
    this.rng = new Float32Array(this.nGroup * 4);
    this.setCaps(caps, groups);

    this.ch = new Float32Array(8 * 4);      // (age, halfWidth, amp, -) per chirp
    this.cent = new Float32Array(24);       // uploaded as 6 vec4s
    this.refl4 = new Float32Array(8);
    this.refl4.set(this.refl.subarray(0, Math.min(6, this.refl.length)));
    this.probeDir = new Float32Array(16 * 4);

    this.fbo = { scene: null, a: null, b: null, probe: null };
    this.w = 0; this.h = 0;
    this._makeProbe();
  }

  setCaps(caps, groups) {
    for (let i = 0; i < caps.length; i++) {
      const r = caps[i];
      this.capA[i * 4] = r[0]; this.capA[i * 4 + 1] = r[1]; this.capA[i * 4 + 2] = r[2]; this.capA[i * 4 + 3] = r[6];
      this.capB[i * 4] = r[3]; this.capB[i * 4 + 1] = r[4]; this.capB[i * 4 + 2] = r[5]; this.capB[i * 4 + 3] = r[7];
    }
    for (let g = 0; g < groups.length; g++) {
      const G = groups[g];
      this.grp[g * 4] = G.cx; this.grp[g * 4 + 1] = G.cy; this.grp[g * 4 + 2] = G.cz; this.grp[g * 4 + 3] = G.rad;
      this.rng[g * 4] = G.from; this.rng[g * 4 + 1] = G.to;
    }
  }

  _tex(w, h, internal, filter) {
    const gl = this.gl, t = gl.createTexture();
    gl.bindTexture(gl.TEXTURE_2D, t);
    gl.texStorage2D(gl.TEXTURE_2D, 1, internal, w, h);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, filter);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, filter);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);
    return t;
  }
  _target(w, h, internal, filter) {
    const gl = this.gl;
    const tex = this._tex(w, h, internal, filter);
    const fb = gl.createFramebuffer();
    gl.bindFramebuffer(gl.FRAMEBUFFER, fb);
    gl.framebufferTexture2D(gl.FRAMEBUFFER, gl.COLOR_ATTACHMENT0, gl.TEXTURE_2D, tex, 0);
    gl.bindFramebuffer(gl.FRAMEBUFFER, null);
    return { fb, tex, w, h };
  }
  _makeProbe() {
    /* 32 rays, marched on the GPU, read back as floats so the page can hold
       the shader's own distance field against the JS one every second */
    this.probe = this._target(16, 1, this.gl.RGBA32F, this.gl.NEAREST);
    this.probeBuf = new Float32Array(16 * 4);
  }

  resize(w, h) {
    if (w === this.w && h === this.h) return;
    const gl = this.gl;
    for (const k of ['scene', 'a', 'b']) if (this.fbo[k]) { gl.deleteFramebuffer(this.fbo[k].fb); gl.deleteTexture(this.fbo[k].tex); }
    this.w = w; this.h = h;
    const qw = Math.max(2, w >> 2), qh = Math.max(2, h >> 2);
    this.fbo.scene = this._target(w, h, gl.RGBA16F, gl.LINEAR);
    this.fbo.a = this._target(qw, qh, gl.RGBA16F, gl.LINEAR);
    this.fbo.b = this._target(qw, qh, gl.RGBA16F, gl.LINEAR);
  }

  _bindMarch(S, probe) {
    const gl = this.gl, u = this.uMarch;
    gl.useProgram(this.pMarch);
    gl.uniform4fv(u.uCapA, this.capA);
    gl.uniform4fv(u.uCapB, this.capB);
    gl.uniform4fv(u.uGroup, this.grp);
    gl.uniform4fv(u.uRange, this.rng);
    gl.uniform3fv(u.uMoth, S.moth);
    gl.uniform3fv(u.uEye, S.eye);
    gl.uniform3fv(u.uFwd, S.fwd);
    gl.uniform3fv(u.uRight, S.right);
    gl.uniform3fv(u.uUp, S.up);
    gl.uniform1f(u.uTanHalf, S.tanHalf);
    gl.uniform4fv(u.uCh, this.ch);
    gl.uniform1i(u.uNCh, S.nCh);
    gl.uniform1f(u.uInvHalfPath, S.invHalfPath);
    gl.uniform1f(u.uAlpha2, S.alpha2);
    gl.uniform1f(u.uKa, S.ka);
    gl.uniform1f(u.uTau, S.tau);
    gl.uniform1f(u.uGain, S.gain);
    gl.uniform1f(u.uRing, S.ring);
    gl.uniform4fv(u.uRefl, this.refl4);
    gl.uniform4fv(u.uCent, this.cent);
    gl.uniform1f(u.uCentMax, S.centMax);
    gl.uniform1f(u.uMothFlick, S.mothFlick);
    gl.uniform1f(u.uProbe, probe ? 1 : 0);
    gl.uniform2f(u.uRes, probe ? 16 : this.w, probe ? 1 : this.h);
  }

  /* Ask the GPU to march 32 given directions and hand the distances back.
     The page compares them with orchard.mjs's own march(). */
  probeDistances(S, dirs) {
    const gl = this.gl;
    const n = Math.min(16, Math.floor(dirs.length / 3));
    this.probeDir.fill(0);
    for (let i = 0; i < n; i++) {
      this.probeDir[i * 4] = dirs[i * 3];
      this.probeDir[i * 4 + 1] = dirs[i * 3 + 1];
      this.probeDir[i * 4 + 2] = dirs[i * 3 + 2];
    }
    gl.bindFramebuffer(gl.FRAMEBUFFER, this.probe.fb);
    gl.viewport(0, 0, 16, 1);
    gl.bindVertexArray(this.vao);
    this._bindMarch(S, true);
    gl.uniform4fv(this.uMarch.uProbeDir, this.probeDir);
    gl.drawArrays(gl.TRIANGLES, 0, 3);
    gl.readPixels(0, 0, 16, 1, gl.RGBA, gl.FLOAT, this.probeBuf);
    gl.bindFramebuffer(gl.FRAMEBUFFER, null);
    const out = [];
    for (let i = 0; i < n; i++) out.push({ t: this.probeBuf[i * 4], mat: Math.round(this.probeBuf[i * 4 + 1]) });
    return out;
  }

  draw(S) {
    const gl = this.gl;
    gl.bindVertexArray(this.vao);
    gl.disable(gl.DEPTH_TEST);
    gl.disable(gl.BLEND);

    gl.bindFramebuffer(gl.FRAMEBUFFER, this.fbo.scene.fb);
    gl.viewport(0, 0, this.w, this.h);
    this._bindMarch(S, false);
    gl.uniform2f(this.uMarch.uRes, this.w, this.h);
    gl.drawArrays(gl.TRIANGLES, 0, 3);

    /* bright pass */
    const q = this.fbo.a;
    gl.bindFramebuffer(gl.FRAMEBUFFER, q.fb);
    gl.viewport(0, 0, q.w, q.h);
    gl.useProgram(this.pBright);
    gl.activeTexture(gl.TEXTURE0); gl.bindTexture(gl.TEXTURE_2D, this.fbo.scene.tex);
    gl.uniform1i(this.uBright.uSrc, 0);
    gl.uniform2f(this.uBright.uSrcTexel, 1 / this.w, 1 / this.h);
    gl.uniform1f(this.uBright.uThresh, S.bloomThresh);
    gl.drawArrays(gl.TRIANGLES, 0, 3);

    /* two separable passes */
    for (const [src, dst, dir] of [[this.fbo.a, this.fbo.b, [1, 0]], [this.fbo.b, this.fbo.a, [0, 1]]]) {
      gl.bindFramebuffer(gl.FRAMEBUFFER, dst.fb);
      gl.viewport(0, 0, dst.w, dst.h);
      gl.useProgram(this.pBlur);
      gl.activeTexture(gl.TEXTURE0); gl.bindTexture(gl.TEXTURE_2D, src.tex);
      gl.uniform1i(this.uBlur.uSrc, 0);
      gl.uniform2f(this.uBlur.uTexel, 1 / dst.w, 1 / dst.h);
      gl.uniform2f(this.uBlur.uDir, dir[0], dir[1]);
      gl.drawArrays(gl.TRIANGLES, 0, 3);
    }

    gl.bindFramebuffer(gl.FRAMEBUFFER, null);
    gl.viewport(0, 0, this.canvas.width, this.canvas.height);
    gl.useProgram(this.pComp);
    gl.activeTexture(gl.TEXTURE0); gl.bindTexture(gl.TEXTURE_2D, this.fbo.scene.tex);
    gl.activeTexture(gl.TEXTURE1); gl.bindTexture(gl.TEXTURE_2D, this.fbo.a.tex);
    gl.uniform1i(this.uComp.uScene, 0);
    gl.uniform1i(this.uComp.uBloom, 1);
    gl.uniform2f(this.uComp.uSceneTexel, 1 / this.canvas.width, 1 / this.canvas.height);
    gl.uniform2f(this.uComp.uBloomTexel, 1 / this.canvas.width, 1 / this.canvas.height);
    gl.uniform1f(this.uComp.uBloomAmt, S.bloom);
    gl.uniform1f(this.uComp.uVig, 0.32);
    gl.drawArrays(gl.TRIANGLES, 0, 3);
  }
};
