/* ═══════════════════════════════════════════════════════════════════════════
   sky.js — "The Survey of Heaven": the front door's personal night sky.

   A cross-page metagame whose visible surface IS the estate map. The dark
   margins of the surveyor's plate are a night sky that RECORDS WHERE YOU HAVE
   BEEN. First visit to any room kindles a star over the dark band beside it;
   rooms in the same WING are joined by a faint asterism line; visiting ALL of a
   wing's members COMPLETES its asterism (lines brighten to brass; an engraved
   name + a one-line myth appear in the margin); completing every wing fires an
   all-skies capstone.

   It reads the `ws:seen:<id>` breadcrumb that EVERY page already drops, so it
   needs NO per-page instrumentation. Always-visible, MONOTONE (visiting more
   only ever ADDS — never removes a star/line/completion), never gated,
   cosmetics-only. It never confers access and touches NO existing predicate.

   The workshop's celestial vein, third register: Firmament invents skies, the
   Orrery shows the real one, the Almanac reads real ephemeris — and the Survey
   of Heaven maps YOUR visits onto a personal sky.

   Vanilla, ES5-ish, zero-dependency. A pure, DOM-free core (state/CATALOG/WINGS)
   + a thin DOM renderer (renderInto/bootstrap). Reads cross-page state from the
   SAME `ws:` bucket via the existing WS global; writes ONLY new cosmetic
   namespaced flags (`ws:flag:sky-<id>-named`, `ws:flag:sky-bootstrap`,
   `ws:flag:firmament-survey`) — additive, affecting no existing predicate.

   Inlined into the front door VIA forge (`<!-- forge:include tools/sky/sky.js
   -->`); forge strips the module guard at the bottom. In a browser this attaches
   a `Sky` global; in Node it exports the same object for the self-test.
   ═══════════════════════════════════════════════════════════════════════════ */
(function (root) {
  'use strict';

  var Sky = {};

  /* CATALOG-POLAR BEGIN */
  /* GENERATED by tools/sky/derive-sky.mjs --emit — DO NOT hand-edit.
     Positions HANG on the derived polar ring (§3.1/§3.2); the source of truth is
     catalog-polar.mjs + the live solve. Re-run derive-sky after any layout change;
     derive-sky --check joins the estate gates (fails when this slab is stale). */
  var CATALOG = {
    "context-window": { x: 750, y: 549.3, mag: 1 },
    "temperature-dial": { x: 724, y: 593.3, mag: 2 },
    "the-turn": { x: 784, y: 633.3, mag: 2 },
    "partition": { x: 650, y: 637.3, mag: 2 },
    "pin-barrel": { x: 253.2, y: 1952.2, mag: 1 },
    "mirror-drum": { x: 295.2, y: 1925.2, mag: 2 },
    "firmament": { x: 305.3, y: 1321.3, mag: 1 },
    "orrery": { x: 305.3, y: 1471.3, mag: 2 },
    "lodestone-hall": { x: 1735.7, y: 2812.2, mag: 1 },
    "bootstrap-bench": { x: 1855.7, y: 2824.2, mag: 1 },
    "compositor": { x: 2353.5, y: 620.6, mag: 1 },
    "blazon": { x: 2453.5, y: 644.6, mag: 2 },
    "the-shepherd": { x: 2621.3, y: 1511.6, mag: 1 },
    "the-standing-stones": { x: 2561.4, y: 1513.6, mag: 2 },
    "feat-rainbow": { x: 130.3, y: 1621.8, mag: 1 },
    "feat-iridescence": { x: 173.5, y: 1665.7, mag: 2 },
    "feat-spyglass": { x: 186.8, y: 1738.6, mag: 2 },
    "feat-spectroscope": { x: 206, y: 1863.1, mag: 2 },
    "feat-maze": { x: 179.7, y: 1927.9, mag: 1 },
    "feat-polariser": { x: 133.7, y: 1866.2, mag: 2 },
    "feat-camera": { x: 110.9, y: 1758.4, mag: 2 },
    "feat-halo": { x: 101.9, y: 1686.9, mag: 2 },
    "feat-anamorphosis": { x: 158.1, y: 1801.7, mag: 2 },
    "carnot": { x: 2913.6, y: 1955.4, mag: 1 },
    "demon": { x: 2861.4, y: 2026.2, mag: 2 },
    "brownian": { x: 2863.4, y: 2111.6, mag: 2 },
    "stirling": { x: 2798.1, y: 2220.1, mag: 2 },
    "strange-garden": { x: 1368, y: 2791.1, mag: 1 },
    "tessellarium": { x: 1468, y: 2799.1, mag: 2 },
    "daedalus": { x: 2692.4, y: 1978.6, mag: 1 },
    "ariadne": { x: 2712.4, y: 2098.6, mag: 2 },
    "verse": { x: 1116.8, y: 345.3, mag: 1 },
    "scriptorium": { x: 1206.8, y: 369.3, mag: 2 },
    "refraction-run": { x: 605.6, y: 1855.5, mag: 1 },
    "starlight-bend": { x: 546.6, y: 1874.7, mag: 2 },
    "cartographer": { x: 405.6, y: 1947.6, mag: 1 },
    "bastion": { x: 337.6, y: 2007.6, mag: 2 },
    "differential-gear": { x: 2587.8, y: 2215.7, mag: 1 },
    "ball-and-disk": { x: 2587.8, y: 2283.7, mag: 2 },
    "tone-mill": { x: 275.6, y: 1799, mag: 1 },
    "singing-plate": { x: 275.6, y: 1748, mag: 2 },
    "hexapawn": { x: 2665.3, y: 2104.7, mag: 2 },
    "the-long-chain": { x: 2645.3, y: 2169.7, mag: 1 },
    "holonomy": { x: 508.9, y: 2160.5, mag: 1 },
    "unrolled-cone": { x: 418.9, y: 2190.5, mag: 2 },
    "belief-beam": { x: 2757.1, y: 2081.4, mag: 1 },
    "likelihood-sluice": { x: 2757.1, y: 2143.4, mag: 2 },
    "aerodrome": { x: 604.8, y: 698.9, mag: 1 },
    "arcade": { x: 2765.8, y: 1245.6, mag: 1 },
    "benford-mill": { x: 1080.3, y: 2709, mag: 2 },
    "collisions": { x: 2765.9, y: 1944.4, mag: 1 },
    "estate-gate": { x: 1549, y: 2902, mag: 1 },
    "glasshouse-range": { x: 768.6, y: 2584.7, mag: 1 },
    "gnomon": { x: 2750.6, y: 1111.7, mag: 1 },
    "museum": { x: 2729.5, y: 1047.9, mag: 1 },
    "orbit-house": { x: 536.7, y: 786.2, mag: 1 },
    "sound-garden": { x: 2827, y: 1660.8, mag: 2 },
    "the-barrel-house": { x: 336.1, y: 1806.8, mag: 1 },
    "the-drawing-room": { x: 789.5, y: 2556.9, mag: 1 },
    "the-heap": { x: 705.2, y: 2453.9, mag: 1 },
    "the-keystone-arch": { x: 2537.8, y: 2349.7, mag: 1 },
    "the-long-way-home": { x: 320.3, y: 1721.7, mag: 1 },
    "the-rolling-room": { x: 2704.8, y: 2137.9, mag: 1 },
    "the-sightline": { x: 273.3, y: 1301, mag: 1 },
    "theogony": { x: 2301.1, y: 2547.1, mag: 2 },
    "threshold": { x: 2797.2, y: 1439.8, mag: 1 },
    "undercroft": { x: 2070.8, y: 2668, mag: 2 },
    "workbench": { x: 1851.6, y: 2762.8, mag: 1 },
  };
  var SKY_GROUPS = {"automaton":{"theta":319,"rOff":20,"lane":null,"hang":0},"carillonneur":{"theta":253,"rOff":20,"lane":null,"hang":0},"celestial":{"theta":277,"rOff":20,"lane":null,"hang":0},"coilwright":{"theta":169,"rOff":20,"lane":null,"hang":0},"design":{"theta":43,"rOff":20,"lane":null,"hang":0},"drover":{"theta":88,"rOff":-190,"lane":"east-lane","hang":88},"feats":{"theta":261,"rOff":20,"lane":null,"hang":-8.8},"furnace":{"theta":112,"rOff":20,"lane":null,"hang":19.2},"garden":{"theta":186,"rOff":20,"lane":null,"hang":0},"labyrinth":{"theta":113,"rOff":20,"lane":null,"hang":0},"letters":{"theta":342,"rOff":20,"lane":null,"hang":0},"pilot":{"theta":252,"rOff":-210,"lane":"west-lane","hang":72},"realm":{"theta":250,"rOff":20,"lane":null,"hang":0},"reckoner":{"theta":124,"rOff":20,"lane":null,"hang":0},"sirenist":{"theta":260,"rOff":20,"lane":null,"hang":0},"strategist":{"theta":118,"rOff":20,"lane":null,"hang":0},"surveyor":{"theta":240,"rOff":20,"lane":null,"hang":0},"wagerer":{"theta":115,"rOff":20,"lane":null,"hang":0}};
  var SKY_HINTS = {"automaton":"Models its own making; keeps none of it.","carillonneur":"Sets the pins, then lets the turning hand be the only clock.","celestial":"Invents a sky; reads the true one.","coilwright":"Makes the current by moving; pays for every spark.","design":"Letter and shield, one measure.","drover":"Never pushes the flock; only chooses where to stand.","feats":"Bends every ray to its purpose.","furnace":"Turns heat to work; never quite all of it.","garden":"Tends the tile till the pattern comes true.","labyrinth":"Builds the turning; keeps the way back.","letters":"Speaks the verse; copies it fair.","pilot":"Flies the least-time road; falls into the law.","realm":"Draws the coast; raises the keep.","reckoner":"Reckons by measuring a shape; one reads the mean, one the integral.","sirenist":"Spins the rate you watch into the pitch you hear.","strategist":"Wins by the move that looks like a mistake.","surveyor":"Walks the loop; brings home the twist no chart can hide.","wagerer":"Pours belief, never spills it; lets the evidence decide the level.","aerodrome":"an unvisited hall of THE OBSERVATORY RISE","arcade":"an unvisited hall of THE FAIRGROUND","benford-mill":"an unvisited hall of THE NUMBER GARDEN","collisions":"an unvisited hall of THE NUMBER GARDEN","estate-gate":"the lantern over the estate's front gate","glasshouse-range":"an unvisited hall of THE GLASSHOUSE GARDENS","gnomon":"an unvisited hall of THE PROMENADES","museum":"an unvisited hall of THE MANOR HOUSE","orbit-house":"an unvisited hall of THE OBSERVATORY RISE","sound-garden":"an unvisited hall of THE MANOR HOUSE","the-barrel-house":"an unvisited hall of THE MANOR HOUSE","the-drawing-room":"an unvisited hall of THE NUMBER GARDEN","the-heap":"an unvisited hall of THE FAIRGROUND","the-keystone-arch":"an unvisited hall of THE WORKS","the-long-way-home":"an unvisited hall of THE PROMENADES","the-rolling-room":"an unvisited hall of THE FAIRGROUND","the-sightline":"an unvisited hall of THE OBSERVATORY RISE","theogony":"an unlit corner of the estate — a room you have yet to enter","threshold":"an unvisited hall of THE MANOR HOUSE","undercroft":"an unvisited hall of THE MANOR HOUSE","workbench":"an unvisited hall of THE MAKER'S SHED"};
  /* STAR_META (§3.3) — id → {name, href?, hidden?} from the estate manifest; the
     W3.4 card layer reads names from here. hidden ⇒ name+link only once ws:seen. */
  var STAR_META = {
    "firmament": {"name":"The Observatory","href":"firmament/index.html"},
    "orrery": {"name":"Orrery","href":"orrery/index.html"},
    "lodestone-hall": {"name":"The Lodestone Hall","href":"lodestone-hall/index.html"},
    "bootstrap-bench": {"name":"The Bootstrap Bench","href":"bootstrap-bench/index.html"},
    "compositor": {"name":"The Print Room","href":"compositor/index.html"},
    "blazon": {"name":"Blazon","href":"blazon/index.html"},
    "the-shepherd": {"name":"The Arcade · The Fold","href":"the-shepherd/index.html"},
    "the-standing-stones": {"name":"The Arcade · The Drover","href":"the-standing-stones/index.html"},
    "strange-garden": {"name":"The Gardens · Glasshouse","href":"strange-garden/index.html"},
    "tessellarium": {"name":"Tessellarium","href":"tessellarium/index.html"},
    "daedalus": {"name":"The Hedge Maze","href":"daedalus/index.html"},
    "ariadne": {"name":"Ariadne","href":"ariadne/index.html"},
    "verse": {"name":"The Study","href":"verse/index.html"},
    "scriptorium": {"name":"Scriptorium","href":"scriptorium/index.html"},
    "refraction-run": {"name":"The Photon's Errand","href":"refraction-run/index.html"},
    "starlight-bend": {"name":"The Light That Falls Around a Star","href":"starlight-bend/index.html","hidden":true},
    "cartographer": {"name":"The Map Room","href":"cartographer/index.html"},
    "bastion": {"name":"Bastion","href":"bastion/index.html"},
    "differential-gear": {"name":"The Differential Gear","href":"differential-gear/index.html"},
    "ball-and-disk": {"name":"The Ball-and-Disk Integrator","href":"ball-and-disk/index.html"},
    "tone-mill": {"name":"The Tone Mill","href":"tone-mill/index.html"},
    "singing-plate": {"name":"The Singing Plate","href":"singing-plate/index.html"},
    "hexapawn": {"name":"The Matchbox That Learns","href":"hexapawn/index.html"},
    "the-long-chain": {"name":"The Long Chain","href":"the-long-chain/index.html"},
    "holonomy": {"name":"Curved Country","href":"holonomy/index.html"},
    "unrolled-cone": {"name":"The Unrolled Cone","href":"unrolled-cone/index.html"},
    "belief-beam": {"name":"The Belief Beam","href":"belief-beam/index.html"},
    "likelihood-sluice": {"name":"The Likelihood Sluice","href":"likelihood-sluice/index.html"},
    "aerodrome": {"name":"The Aerodrome","href":"aerodrome/index.html"},
    "arcade": {"name":"The Arcade","href":"arcade/index.html"},
    "benford-mill": {"name":"The Benford Mill","href":"benford-mill/index.html"},
    "collisions": {"name":"The Clack Counter","href":"collisions/index.html"},
    "estate-gate": {"name":"The Gate","href":"the-gate/the-gate.html"},
    "glasshouse-range": {"name":"The Glasshouse Range","href":"glasshouse-range/index.html"},
    "gnomon": {"name":"The Hours","href":"hours/index.html"},
    "museum": {"name":"The Museum","href":"museum/index.html"},
    "orbit-house": {"name":"The Orbit House","href":"orbit-house/index.html"},
    "sound-garden": {"name":"The Music Room","href":"sound-garden/index.html"},
    "the-barrel-house": {"name":"The Barrel House","href":"the-barrel-house/index.html"},
    "the-drawing-room": {"name":"The Drawing Room","href":"the-drawing-room/index.html"},
    "the-heap": {"name":"The Gardens · The Assayer's Tray","href":"the-heap/index.html"},
    "the-keystone-arch": {"name":"The Stoneyard","href":"the-keystone-arch/index.html"},
    "the-long-way-home": {"name":"The Long Way Home","href":"the-long-way-home/index.html"},
    "the-rolling-room": {"name":"The Gardens · The Rolling Room","href":"the-rolling-room/index.html"},
    "the-sightline": {"name":"The Sightline","href":"the-sightline/index.html"},
    "theogony": {"name":"Theogony","href":"theogony/index.html"},
    "threshold": {"name":"The East Wing · Threshold","href":"threshold/index.html"},
    "undercroft": {"name":"The Undercroft · Beneath","href":"undercroft/index.html"},
    "workbench": {"name":"The Maker's Shed","href":"workbench/index.html"},
  };
  Sky.STAR_META = STAR_META;
  /* CATALOG-POLAR END */

  /* ── DATA: the six wings (companion-pairs), each an asterism ────────────────
     `members` are catalog ids; the line threads them in listed order. `name` is
     the engraved label that appears in the margin once complete; `myth` is its
     one-line Oracle-flavoured legend. Order of members is the polyline order. */
  var WINGS = [
    { id: 'celestial', name: 'The Astronomer',   members: ['firmament', 'orrery'],
      myth: 'Invents a sky; reads the true one.' },
    { id: 'design',    name: 'The Compositor',   members: ['compositor', 'blazon'],
      myth: 'Letter and shield, one measure.' },
    { id: 'labyrinth', name: 'The Maze & Thread', members: ['daedalus', 'ariadne'],
      myth: 'Builds the turning; keeps the way back.' },
    { id: 'realm',     name: 'The Cartographer', members: ['cartographer', 'bastion'],
      myth: 'Draws the coast; raises the keep.' },
    { id: 'letters',   name: 'The Scribe',       members: ['verse', 'scriptorium'],
      myth: 'Speaks the verse; copies it fair.' },
    { id: 'garden',    name: 'The Gardener',     members: ['strange-garden', 'tessellarium'],
      myth: 'Tends the tile till the pattern comes true.' }
  ];

  /* ── DATA: the feats constellation (a BONUS asterism, NOT a wing) ───────────────
     The Hall of Mirrors' nine "Feats of Light" form their OWN charted constellation,
     drawn + named by the SAME asterism machinery as the six wings — but kept SEPARATE
     so the all-skies capstone (allComplete) stays the original six companion-wings
     ONLY. Earning all nine completes this constellation (brass lines + an engraved
     name + a one-line myth) without ever gating the capstone. Each member is a
     `feat-<X>` pseudo-id, "visited" iff the store holds `ws:flag:earned-<X>`. */
  /* FEATS is an ARRAY of feat-GROUPS (each drawn + named like a wing, but ADDITIVE —
     none ever feeds the all-skies capstone). The Optician (the Hall's nine Feats of
     Light) is unchanged; two new groups reward the orphaned-wing visit trails:
       • The Automaton — Clockwork's 4 benches (plain `ws:seen:<id>` room crumbs)
       • The Furnace   — the Engine Room's 4 benches (plain room crumbs)
     Member order = polyline order; the SET is what gates completion (order-free). */
  var FEATS = [
    { id: 'feats', name: 'The Optician', myth: 'Bends every ray to its purpose.',
      members: ['feat-rainbow', 'feat-iridescence', 'feat-spyglass', 'feat-spectroscope',
                'feat-maze', 'feat-polariser', 'feat-camera', 'feat-halo', 'feat-anamorphosis'] },
    { id: 'automaton', name: 'The Automaton', myth: 'Models its own making; keeps none of it.',
      members: ['context-window', 'temperature-dial', 'the-turn', 'partition'] },
    { id: 'furnace', name: 'The Furnace', myth: 'Turns heat to work; never quite all of it.',
      members: ['carnot', 'demon', 'brownian', 'stirling'] },
    // The Surveyor — Curved Country's reward constellation. Founded with one star
    // (The Holonomy Walk, a plain `ws:seen:holonomy` room crumb); its membership
    // grows as the wing's promised siblings ship (a Gauss-Bonnet polygon, a cone's
    // deficit angle, a curvature-cancelling torus). Like every feat-group it is
    // ADDITIVE — it NEVER feeds the wings-only all-skies capstone.
    { id: 'surveyor', name: 'The Surveyor', myth: 'Walks the loop; brings home the twist no chart can hide.',
      members: ['holonomy', 'unrolled-cone'] },
    // The Strategist — the number wing's solved-games reward constellation: two rooms where you
    // learn to beat a provably perfect opponent. Founded by The Matchbox That Learns (Hexapawn, a
    // machine that teaches itself to stop losing) and grown by The Long Chain (Dots-and-Boxes, won
    // by handing boxes back). Two stars, so the engraved name never sits over a lone dot. ADDITIVE —
    // it never feeds the wings-only all-skies capstone.
    { id: 'strategist', name: 'The Strategist', myth: 'Wins by the move that looks like a mistake.',
      members: ['hexapawn', 'the-long-chain'] },
    // The Pilot — Optics' fly-through reward constellation. Founded by The Photon's Errand
    // (`ws:seen:refraction-run`, fly least-time through slow glass) and grown by The Light
    // That Falls Around a Star (`ws:seen:starlight-bend`, fly the SAME least-time road bent
    // by gravity instead of glass — thread the hidden star, earn the Einstein ring on-axis);
    // the engraved name now sits over TWO dots. Like every feat-group it is ADDITIVE — it
    // NEVER feeds the wings-only all-skies capstone. Sized to keep growing as more piloted
    // least-time scenes ship.
    { id: 'pilot', name: 'The Pilot', myth: 'Flies the least-time road; falls into the law.',
      members: ['refraction-run', 'starlight-bend'] },
    // The Reckoner — the Reckoning Cabinet's reward constellation. Founded with The Differential
    // Gear (the adder) and grown by The Ball-and-Disk Integrator (the integrating organ) — both
    // plain `ws:seen:<id>` room crumbs; the engraved name now sits over TWO stars (the two organs
    // of a differential analyzer), completion requiring both. Like every feat-group it is
    // ADDITIVE — it NEVER feeds the wings-only all-skies capstone. Sized for the cabinet's
    // analog-instrument kin as more reckon-by-measuring scenes ship.
    { id: 'reckoner', name: 'The Reckoner', myth: 'Reckons by measuring a shape; one reads the mean, one the integral.',
      members: ['differential-gear', 'ball-and-disk'] },
    // The Drover — the Arcade's herding reward constellation. Founded by The Shepherd
    // (`ws:seen:the-shepherd`, hold the stick + drive a flock live) and grown by The Standing Stones
    // (`ws:seen:the-standing-stones`, set the stick down — place fixed stones, then release), the same
    // verified flock law as a placement puzzle. The engraved name now sits over TWO dots. Like every
    // feat-group it is ADDITIVE — it NEVER feeds the wings-only all-skies capstone. Sized to keep
    // growing as the amusements' steer-the-living-system kin ship.
    { id: 'drover', name: 'The Drover', myth: 'Never pushes the flock; only chooses where to stand.',
      members: ['the-shepherd', 'the-standing-stones'] },
    // The Coilwright — the Electromagnetism wing's reward constellation. Founded with
    // The Lodestone Hall (`ws:seen:lodestone-hall`) and grown by The Bootstrap Bench
    // (`ws:seen:bootstrap-bench`), the induction vein's capstone; like every feat-group
    // it is ADDITIVE — it NEVER feeds the wings-only all-skies capstone. Sized to keep
    // growing as the vein's promised siblings (an LC tank, a transformer, an eddy brake,
    // a betatron) ship.
    { id: 'coilwright', name: 'The Coilwright', myth: 'Makes the current by moving; pays for every spark.',
      members: ['lodestone-hall', 'bootstrap-bench'] },
    // The Sirenist — the Kinetics & Sound wing's reward constellation. Founded by The Tone
    // Mill (`ws:seen:tone-mill`) and grown by The Singing Plate (`ws:seen:singing-plate`),
    // the driven Chladni plate that SINGS its eigenmode — the same rate→pitch law in a
    // second instrument. Like every feat-group it is ADDITIVE — it NEVER feeds the wings-
    // only all-skies capstone. Sized to keep growing as more of the wing's seen-and-heard
    // kin (a free stroboscope, a tuning-fork beat) ship.
    { id: 'sirenist', name: 'The Sirenist', myth: 'Spins the rate you watch into the pitch you hear.',
      members: ['tone-mill', 'singing-plate'] },
    // The Wagerer — the Belief Beam's reward constellation. Now TWO stars: The Belief Beam (the
    // founding `ws:seen:belief-beam` crumb) and The Likelihood Sluice (`ws:seen:likelihood-sluice`),
    // the same additive log-LR law given two gates so belief decides WHEN to act. Like every
    // feat-group it is ADDITIVE — it NEVER feeds the wings-only all-skies capstone; its engraved name
    // now sits over two stars, and its tally fires only when BOTH crumbs exist. Room for more
    // inference kin (a conjugate-prior dial, a credible-interval lantern) as they ship.
    { id: 'wagerer', name: 'The Wagerer', myth: 'Pours belief, never spills it; lets the evidence decide the level.',
      members: ['belief-beam', 'likelihood-sluice'] },
    // The Carillonneur — the Barrel House's reward constellation (the music-box wing where
    // TIME IS THE CRANK). Founded by The Pin-Barrel (`ws:seen:pin-barrel`, the delay canon)
    // and grown by The Mirror Drum (`ws:seen:mirror-drum`, the crab canon) — the two named
    // founding rooms, so its engraved name sits over TWO stars from the start. Like every
    // feat-group it is ADDITIVE — it NEVER feeds the wings-only all-skies capstone. Sized to
    // keep growing as the wing's named-dark third (The Mensuration Barrel, 2:1) and further
    // music-box kin ship.
    { id: 'carillonneur', name: 'The Carillonneur', myth: 'Sets the pins, then lets the turning hand be the only clock.',
      members: ['pin-barrel', 'mirror-drum'] }
  ];

  Sky.CATALOG = CATALOG;
  Sky.WINGS = WINGS;
  Sky.FEATS = FEATS;
  Sky.GROUPS = SKY_GROUPS;
  Sky.HINTS = SKY_HINTS;

  /* ── STAR-CAUSALITY (§3.3) — the pure, DOM-free half the card layer + the tests share ──
     Every catalog star belongs to exactly ONE group (a wing or a feat-group; sky.test's
     BIJECTION proves it). GROUP_OF resolves a star id → its group record so a card can
     name the group and count how many of its lights are kindled. Built once, iterated in
     WINGS-then-FEATS declaration order (deterministic). */
  var GROUP_OF = {};
  (function () {
    var i, m;
    for (i = 0; i < WINGS.length; i++) for (m = 0; m < WINGS[i].members.length; m++) GROUP_OF[WINGS[i].members[m]] = WINGS[i];
    for (i = 0; i < FEATS.length; i++) for (m = 0; m < FEATS[i].members.length; m++) GROUP_OF[FEATS[i].members[m]] = FEATS[i];
  })();
  Sky.groupOf = function (id) { return GROUP_OF[id] || null; };

  /* house voice for the star-card + sky-index copy: spelled numbers, never numerals
     shorthand (§3.3 / §4.6 leak-watch). Falls back to the numeral above the table. */
  var NUM_WORDS = ['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight',
                   'nine', 'ten', 'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen'];
  Sky.numberWord = function (n) { return (n >= 0 && n < NUM_WORDS.length) ? NUM_WORDS[n] : String(n); };

  Sky.SKYLIT = 'ws:flag:skylit-';   // the per-star first-light flag prefix (§3.3)

  /* Sky.kindlePlan(state, store) — PURE. The lit stars that have NEVER been kindled on
     this origin (their `ws:flag:skylit-<id>` flag is absent), returned BRIGHTEST-FIRST
     (mag ascending) with a stable id tiebreak — the order the DOM layer staggers the
     first-light bloom in (120ms apart), and exactly the set whose flags renderInto sets
     after (whether or not it animated — reduced-motion still arms them). Never mutates. */
  Sky.kindlePlan = function (state, store) {
    var lit = (state && state.stars ? state.stars : []).slice().sort(function (a, b) {
      if (a.mag !== b.mag) return a.mag - b.mag;                 // mag 1 (a wing's bright lead) first
      return a.id < b.id ? -1 : (a.id > b.id ? 1 : 0);           // deterministic tiebreak
    });
    var fresh = [];
    for (var i = 0; i < lit.length; i++) {
      if (lsGet(store, Sky.SKYLIT + lit[i].id) == null) fresh.push(lit[i].id);
    }
    return fresh;
  };

  /* Sky.armReveal(store, ids) — §survey-reveal. Monotonically ARM the first-light /
     first-completion flags the HOLD render deferred, so a revealed star/formation never
     replays its bloom. Call per item as the choreography lights it (crash-safe: a reload
     mid-choreography re-reveals only the not-yet-armed ones). ids = { stars:[id…], asts:[id…] }.
     Idempotent; the Undercroft reset re-arms these the same way renderInto does. */
  Sky.armReveal = function (store, ids) {
    if (!ids) return;
    var i;
    if (ids.stars) for (i = 0; i < ids.stars.length; i++) lsSet(Sky.SKYLIT + ids.stars[i], '1');
    if (ids.asts) for (i = 0; i < ids.asts.length; i++) lsSet('ws:flag:sky-' + ids.asts[i] + '-named', '1');
  };

  /* the spoiler-light HINT for a star: a per-star line if the manifest carried one, else
     its group's one-line myth, else a generic "unlit corner". Never a name, never a link. */
  function hintFor(id) {
    if (SKY_HINTS[id]) return SKY_HINTS[id];
    var grp = GROUP_OF[id];
    if (grp && SKY_HINTS[grp.id]) return SKY_HINTS[grp.id];
    if (grp && grp.myth) return grp.myth;
    return 'an unlit corner of the estate — a room you have yet to enter';
  }

  /* Sky.cardModel(id, visited, store) — PURE. The render-agnostic facts the star card AND
     the sky-index both display (single source, so the two can never drift). `visited` is a
     truthy-map of lit ids (Sky.visitedFromStore); `store` (optional) is consulted ONLY for
     the hidden-star lock: a `hidden:true` star reveals its name+link solely once its own
     `ws:seen:<id>` breadcrumb exists — before that its card is hint-only, the same discipline
     the Register uses (§3.3 / §4.4). A card NEVER reads PLACES; names come from STAR_META.
       { id, lit, hidden, revealed, name?, href?, hint?, group:{ id,name,total,lit,complete } } */
  Sky.cardModel = function (id, visited, store) {
    visited = visited || {};
    var meta = STAR_META[id] || null;
    var lit = !!visited[id];
    var hidden = !!(meta && meta.hidden);
    // reveal the name/link when lit — but a hidden star gates that on its OWN ws:seen crumb.
    var revealed = hidden ? (store && store.has ? !!store.has('ws:seen:' + id) : lit) : lit;
    var grp = GROUP_OF[id];
    var total = grp ? grp.members.length : 0, litCount = 0;
    if (grp) for (var i = 0; i < grp.members.length; i++) if (visited[grp.members[i]]) litCount++;
    var out = {
      id: id, lit: lit, hidden: hidden, revealed: revealed,
      group: grp ? { id: grp.id, name: grp.name, total: total, lit: litCount, complete: total > 0 && litCount === total } : null
    };
    if (revealed && meta) { out.name = meta.name; if (meta.href) out.href = meta.href; }
    else out.hint = hintFor(id);
    return out;
  };

  /* the group-progress line in house voice — "three of its five lights kindled", never a
     numeral shorthand; "all … charted" once complete; a lone light stays singular. */
  Sky.progressLine = function (group) {
    if (!group) return '';
    var w = Sky.numberWord, unit = group.total === 1 ? 'light' : 'lights';
    if (group.complete) return 'all ' + w(group.total) + ' ' + unit + ' kindled — charted';
    return w(group.lit) + ' of its ' + w(group.total) + ' ' + unit + ' kindled';
  };

  /* ── PURE CORE ──────────────────────────────────────────────────────────────
     Sky.state(visited, catalog, wings) — deterministic, ORDER-INDEPENDENT,
     MONOTONE. Given a set/array/map of visited ids it returns:
       stars      [ {id, x, y, mag} ]  — every lit catalog entry (visited)
       lines      [ {wing, points:[[x,y],…], complete} ] — per-wing polyline through
                  the VISITED members (partial allowed; >=2 points to draw a line)
       asterisms  [ {…wing, members, complete: members.every(visited)} ]
       allComplete  true iff every wing is complete
     Visiting more visits only ever turns features ON, never off (monotonicity is
     structural: a superset of `visited` ⊇ the prior lit stars/line points, and
     `complete` is a monotone AND over membership). */
  function toSet(visited) {
    if (!visited) return {};
    var set = {};
    if (typeof visited.has === 'function' && typeof visited.forEach === 'function'
        && typeof visited.size === 'number') {
      // a real Set
      visited.forEach(function (id) { set[id] = true; });
      return set;
    }
    if (Object.prototype.toString.call(visited) === '[object Array]') {
      for (var i = 0; i < visited.length; i++) set[visited[i]] = true;
      return set;
    }
    // a plain object map { id: truthy }
    for (var k in visited) if (Object.prototype.hasOwnProperty.call(visited, k) && visited[k]) set[k] = true;
    return set;
  }

  Sky.state = function (visited, catalog, wings, feats) {
    catalog = catalog || CATALOG;
    wings = wings || WINGS;
    // `feats` may be a single group object, an array of groups, or omitted. It draws
    // + names exactly like a wing, but is kept SEPARATE so it NEVER feeds allComplete.
    if (feats === undefined) feats = FEATS;
    var featGroups = !feats ? [] :
      (Object.prototype.toString.call(feats) === '[object Array]' ? feats : [feats]);
    var vset = toSet(visited);
    var has = function (id) { return !!vset[id]; };

    // lit stars — iterate the catalog in a STABLE key order (insertion order of a
    // plain object is preserved for string keys in every engine we target), so the
    // output is deterministic regardless of the order ids were visited.
    var stars = [];
    var id;
    for (id in catalog) {
      if (!Object.prototype.hasOwnProperty.call(catalog, id)) continue;
      if (!has(id)) continue;
      var c = catalog[id];
      stars.push({ id: id, x: c.x, y: c.y, mag: c.mag });
    }

    // compute one group's line + asterism record (shared by wings and feats)
    function group(g) {
      var members = g.members || [];
      var complete = members.length > 0;
      var pts = [];
      for (var m = 0; m < members.length; m++) {
        var mid = members[m];
        if (!has(mid)) { complete = false; continue; }
        var mc = catalog[mid];
        if (mc) pts.push([mc.x, mc.y]);
      }
      var line = (pts.length >= 2)
        ? { wing: g.id, points: pts, complete: complete } : null;
      var ast = { id: g.id, name: g.name, myth: g.myth, members: members, complete: complete };
      return { line: line, ast: ast, complete: complete };
    }

    var lines = [];
    var asterisms = [];
    // ── the six wings: these (and ONLY these) feed the all-skies capstone ──
    var allComplete = wings.length > 0;
    for (var w = 0; w < wings.length; w++) {
      var gw = group(wings[w]);
      if (!gw.complete) allComplete = false;
      if (gw.line) lines.push(gw.line);
      asterisms.push(gw.ast);
    }
    // ── the feats constellation(s): drawn + named the SAME way, but ADDITIVE — they
    //    do NOT touch allComplete, so the original capstone is unchanged. ──
    for (var f = 0; f < featGroups.length; f++) {
      var gf = group(featGroups[f]);
      if (gf.line) lines.push(gf.line);
      asterisms.push(gf.ast);
    }

    return { stars: stars, lines: lines, asterisms: asterisms, allComplete: allComplete };
  };

  /* ── helpers shared by the DOM layer ──────────────────────────────────────── */
  var SVGNS = 'http://www.w3.org/2000/svg';
  function svg(name, attrs) {
    var e = root.document.createElementNS(SVGNS, name);
    for (var k in attrs) if (Object.prototype.hasOwnProperty.call(attrs, k)) e.setAttribute(k, attrs[k]);
    return e;
  }
  function lsGet(store, k) { return store && store.has(k) ? store.get(k) : null; }
  function lsSet(k, v) { try { localStorage.setItem(k, v); return true; } catch (e) { return false; } }

  /* Build the visited set from a WS store snapshot. Room stars come from the
     `ws:seen:<id>` breadcrumb every page drops; the feats constellation's `feat-<X>`
     pseudo-stars come from the raise-only `ws:flag:earned-<X>` Hall-of-Mirrors flags
     (e.g. `ws:flag:earned-rainbow` → `feat-rainbow`). Both are additive. */
  Sky.visitedFromStore = function (store) {
    var v = {};
    if (!store || !store.ok || !store.all) return v;
    var SEEN = 'ws:seen:', EARNED = 'ws:flag:earned-';
    for (var k in store.all) {
      if (!Object.prototype.hasOwnProperty.call(store.all, k)) continue;
      if (k.indexOf(SEEN) === 0) v[k.slice(SEEN.length)] = true;
      else if (k.indexOf(EARNED) === 0) v['feat-' + k.slice(EARNED.length)] = true;
    }
    return v;
  };

  /* ── Sky.bootstrap(store) ────────────────────────────────────────────────────
     On the FIRST ever run on this origin (ws:flag:sky-bootstrap absent), silently
     mark every ALREADY-complete asterism's `ws:flag:sky-<id>-named` flag — so a
     returning visitor who already completed wings before this feature existed gets
     NO retroactive name-in animation. Then set ws:flag:sky-bootstrap. Idempotent.
     Mirrors WS.bootstrap. */
  Sky.bootstrap = function (store) {
    if (!store) { try { store = root.WS && root.WS.store(); } catch (e) { store = null; } }
    if (!store || !store.ok) return;
    if (lsGet(store, 'ws:flag:sky-bootstrap') != null) return;
    var st = Sky.state(Sky.visitedFromStore(store), CATALOG, WINGS);
    for (var i = 0; i < st.asterisms.length; i++) {
      var a = st.asterisms[i];
      if (a.complete) lsSet('ws:flag:sky-' + a.id + '-named', '1');
    }
    lsSet('ws:flag:sky-bootstrap', '1');
  };

  /* ── Sky.renderInto(sheet, PLACES, store, world) ─────────────────────────────
     Draw a `<g class="sky">` as the FIRST child of #sheet (stars sit "in the
     paper", behind the grid/footprints). PLACES is accepted for parity with the
     map's render signature (the sky reads from the ws: store, not PLACES). `world`
     is the solved §1.7 extent (`Layout.world` — W/H/viewBox); the Survey tally is
     anchored to the WORLD-DERIVED SE dark margin from it (the retired 1440×900
     corner is dead). Omitting `world` falls back to that old corner (harmless for
     any DOM render that hands us no world). */
  Sky.renderInto = function (sheet, PLACES, store, world, opts) {
    if (!root || !root.document || !sheet) return null;
    if (!store) { try { store = root.WS && root.WS.store(); } catch (e) { store = null; } }
    if (!store || !store.ok) return null;   // storage off → no sky (degrade to nothing)

    // ── HOLD mode (opt-in, §survey-reveal): the caller runs a GUIDED reveal choreography
    //    (fly the camera to each newly-charted formation, then light it in step). Under hold
    //    the FRESH items (never-kindled stars, first-completed lines/names) render in their
    //    PRE-reveal state and their first-light/name flags are NOT armed — the front door
    //    lights each at the right camera moment (adding the same .kindling/.brighten-in/.inking
    //    /.named-in classes this renderer would have) and then calls Sky.armReveal(). The
    //    DEFAULT path (opts absent) is byte-identical to before — the sky self-test is untouched.
    var hold = !!(opts && opts.hold);

    var reduce = false;
    try { reduce = root.matchMedia && root.matchMedia('(prefers-reduced-motion: reduce)').matches; } catch (e) {}

    var vmap = Sky.visitedFromStore(store);
    var st = Sky.state(vmap, CATALOG, WINGS);

    // ── FIRST-LIGHT plan (§3.3): the lit stars never yet kindled on this origin, brightest
    //    first. Their `.kindling` bloom is staggered 120ms apart; their flags are SET after
    //    the loop (under reduced-motion we skip the bloom but STILL arm the flags). ──
    var fresh = Sky.kindlePlan(st, store);
    var kindleOrder = {};
    for (var ki = 0; ki < fresh.length; ki++) kindleOrder[fresh[ki]] = ki;

    // ── ASTERISM FIRST-COMPLETION plan (§3.3): a wing charted for the FIRST time this render
    //    (complete + its `-named` flag still absent) drives, before the name fades in, a
    //    member-by-member brighten (240ms apart, members order) then a line-by-line ink. We
    //    read the flags here and set them in the name loop below (one flag, one firing). ──
    var firstNamed = {};               // wingId → { order:{id→idx}, count }
    for (var ai = 0; ai < st.asterisms.length; ai++) {
      var a0 = st.asterisms[ai];
      if (!a0.complete) continue;
      if (lsGet(store, 'ws:flag:sky-' + a0.id + '-named') != null) continue;
      var ord = {};
      for (var mi = 0; mi < a0.members.length; mi++) ord[a0.members[mi]] = mi;
      firstNamed[a0.id] = { order: ord, count: a0.members.length };
    }

    // remove a prior render (idempotent re-render)
    var old = sheet.querySelector('g.sky');
    if (old && old.parentNode) old.parentNode.removeChild(old);

    // The sky <g> is NOT blanket aria-hidden: it now carries ONE actionable, announced control
    // (the Survey tally button that opens the accessible sky index). Its decorative parts — the
    // bare star/line/leader shapes (presentational SVG, not announced), the hit discs, the
    // sub-tallies, and the engraved names — are individually aria-hidden so the tally-button is
    // the only thing the a11y tree sees here (the stars themselves would be ~65 hostile stops).
    var g = svg('g', { 'class': 'sky' });

    // ── asterism lines (under the stars) ──
    var i, j;
    for (i = 0; i < st.lines.length; i++) {
      var ln = st.lines[i];
      var d = '';
      for (j = 0; j < ln.points.length; j++) {
        d += (j === 0 ? 'M' : 'L') + ln.points[j][0] + ' ' + ln.points[j][1] + ' ';
      }
      var freshLine = ln.complete && !!firstNamed[ln.wing];       // this line charts THIS render
      var inkFirst = freshLine && !reduce && !hold;
      // under hold a first-completing line stays in its PRE-reveal look (faint, NOT .complete);
      // the choreography adds `.complete .inking` when the camera reaches it. `sky-hold-line`
      // marks it so the front door can find + reveal it.
      var showComplete = ln.complete && !(hold && freshLine);
      var pl = svg('path', {
        'class': 'asterism-line' + (showComplete ? ' complete' : '') + (inkFirst ? ' inking' : '') +
                 (hold && freshLine ? ' sky-hold-line' : ''),
        d: d.trim(), 'data-wing': ln.wing
      });
      if (inkFirst) {
        // draw the figure line-by-line AFTER its members have brightened (count·240ms).
        pl.setAttribute('pathLength', '1');
        pl.style.animationDelay = (firstNamed[ln.wing].count * 240) / 1000 + 's';
      }
      g.appendChild(pl);
    }

    // member ids of every COMPLETED asterism — drawn as brighter "anchor" stars so a
    // charted constellation reads as a NAMED LINE JOINING TWO VISIBLE STARS, not a
    // hairline trailing off to faint points (the legibility fix of 2026-06-13).
    var chartedIds = {};
    for (i = 0; i < st.asterisms.length; i++) {
      if (!st.asterisms[i].complete) continue;
      var mm = st.asterisms[i].members || [];
      for (j = 0; j < mm.length; j++) chartedIds[mm[j]] = true;
    }

    // when a one-shot bloom/brighten ends, drop its class so the steady twinkle resumes at a
    // staggered phase (never a competing infinite+one-shot animation on the same element).
    function settleAfterAnim(star, twinkleDelay) {
      star.addEventListener('animationend', function () {
        star.classList.remove('kindling'); star.classList.remove('brighten-in');
        star.style.animationDelay = twinkleDelay;
      }, { once: true });
    }

    // ── stars (twinkling circles; static under reduced-motion) ──
    for (i = 0; i < st.stars.length; i++) {
      var s = st.stars[i];
      var chartedFinal = !!chartedIds[s.id];      // member of a complete asterism (final state)
      // BUG#3: the sky rides the plate's scale(k); at fit view the 3100 world maps to
      // ~0.4× screen, so the old ~1.6–2.6 world-unit dots rendered ~1px and vanished.
      // Bump the base radii (~1.8×) so lit stars read as points at fit view; their CSS
      // drop-shadow glow does the rest. Still modest ornament when zoomed in. Radius keys on
      // the FINAL charted state (never changes on reveal — the class does, not the size).
      var rad = (s.mag === 1 ? 4.6 : (s.mag === 2 ? 3.6 : 2.8)) + (chartedFinal ? 1.3 : 0);
      // first-light bloom (this star has never kindled) vs first-completion brighten (an
      // already-lit member of a wing charting for the first time this render). The freshly-lit
      // completing member is the one that kindles; its already-lit siblings brighten in turn.
      var fnWing = chartedFinal ? firstNamed[GROUP_OF[s.id] ? GROUP_OF[s.id].id : ''] : null;
      var isFresh = kindleOrder[s.id] != null;                        // never kindled → blooms
      // under HOLD, a star that would animate (fresh, or an already-lit member of a charting
      // formation) is DEFERRED to the choreography: its .charted brass + its animation are held
      // and the front door lights it at the camera moment. `sky-hold` marks it; `data-fresh`
      // marks the never-lit ones (CSS hides those to 0 until they bloom).
      var willReveal = hold && (isFresh || !!fnWing);
      var charted = chartedFinal && !willReveal;
      var kindling = !hold && !reduce && isFresh;
      var brightenIn = !hold && !reduce && !kindling && !!fnWing;
      var cls = 'sky-star mag' + s.mag + (charted ? ' charted' : '') +
                (kindling ? ' kindling' : '') + (brightenIn ? ' brighten-in' : '') +
                (willReveal ? ' sky-hold' : '');
      var star = svg('circle', { cx: s.x, cy: s.y, r: rad, 'class': cls, 'data-id': s.id });
      if (willReveal && isFresh) star.setAttribute('data-fresh', '1');
      var twinkleDelay = ((s.x * 7 + s.y * 13) % 4000) / 1000 + 's';
      if (kindling) { star.style.animationDelay = (kindleOrder[s.id] * 120) / 1000 + 's'; settleAfterAnim(star, twinkleDelay); }
      else if (brightenIn) { star.style.animationDelay = (fnWing.order[s.id] * 240) / 1000 + 's'; settleAfterAnim(star, twinkleDelay); }
      else if (!reduce && !willReveal) { star.style.animationDelay = twinkleDelay; }   // stagger the shimmer (held stars rest until revealed)
      g.appendChild(star);
    }

    // ── engraved asterism names + myths (in the margin), routed via the map's
    //    label solver upstream; here we just draw the text the caller positioned.
    //    Each complete asterism gets a name once; the FIRST time it becomes
    //    complete (its -named flag absent) we animate it in, then set the flag. ──
    var named = [];
    for (i = 0; i < st.asterisms.length; i++) {
      var a = st.asterisms[i];
      if (!a.complete) continue;
      var firstTime = !!firstNamed[a.id];     // single source with the brighten/ink plan above
      named.push({ ast: a, firstTime: firstTime });
      // under HOLD the front door arms this flag (Sky.armReveal) once the name is revealed, so a
      // reload mid-choreography still re-reveals the un-shown ones. Default path: arm now.
      if (firstTime && !hold) lsSet('ws:flag:sky-' + a.id + '-named', '1');   // one flag, one firing
    }

    // ── FIRST-LIGHT flags: arm every freshly-kindled star's `skylit-<id>` flag now that it
    //    has been drawn (whether or not it animated — reduced-motion still monotonically
    //    arms it, so the bloom never replays). Idempotent; the Undercroft reset re-arms it. ──
    if (!hold) for (i = 0; i < fresh.length; i++) lsSet(Sky.SKYLIT + fresh[i], '1');

    // ── the STAR-CARD hit layer (§3.3): an invisible disc over EVERY catalog star (lit AND
    //    unlit), pointer-events:all so a hover/tap reveals its card — while the painted sky
    //    above stays pointer-events:none. aria-hidden rides the whole sky <g>: ~65 tab stops
    //    on stars would be hostile, so the keyboard surface is the SKY INDEX panel, not these
    //    discs (each is tabindex -1). The page wires the hover/click handlers off `data-id`. ──
    var hit = svg('g', { 'class': 'sky-hit' });
    var catIds = Object.keys(CATALOG);           // stable string-key insertion order (deterministic)
    for (i = 0; i < catIds.length; i++) {
      var cc = CATALOG[catIds[i]];
      hit.appendChild(svg('circle', {
        cx: cc.x, cy: cc.y, r: 10, 'class': 'sky-hit-dot', 'data-id': catIds[i], tabindex: '-1'
      }));
    }
    g.appendChild(hit);

    // expose what was computed so the map's label pass can place the name boxes + the card
    // layer can read the visited set without re-deriving it (single source).
    g.__skyNamed = named;
    g.__skyState = st;
    g.__skyVisited = vmap;
    // §survey-reveal: when held, hand the front door the plan to choreograph then arm.
    // starIds = the fresh (never-kindled) lit ids, brightest-first (kindlePlan order);
    // astIds = the asterisms charting for the FIRST time this render (the formations to fly to).
    g.__skyHeld = hold ? { hold: true, starIds: fresh.slice(), astIds: Object.keys(firstNamed) } : null;

    // ── the margin tally: "Survey of Heaven — N/6 skies charted". The denominator is
    //    the SIX companion-wings only; EVERY feat-group (the Optician + the Automaton +
    //    the Furnace) is a separate bonus and is excluded from the /6 count (each gets
    //    its own sub-tally below). Derive the exclude-set from the SAME FEATS array so a
    //    new feat-group can never be miscounted into the wing tally. ──
    var wingIds = {};
    for (i = 0; i < WINGS.length; i++) wingIds[WINGS[i].id] = true;
    var featGroupIds = {};
    for (i = 0; i < FEATS.length; i++) featGroupIds[FEATS[i].id] = true;
    var charted = 0, wingTotal = WINGS.length;
    for (i = 0; i < st.asterisms.length; i++) {
      var ai = st.asterisms[i];
      if (featGroupIds[ai.id]) continue;                 // a feat-group never counts toward /6
      if (wingIds[ai.id] && ai.complete) charted++;
    }
    // ── §1.7/§4.1 SE-MARGIN anchor (WORLD-DERIVED). The frozen 1440×900 corner
    //    x1414/y862 died with the polar reorg — on the 3100² world it now falls at
    //    upper-CENTRE, over live plate content (T3.6). Re-anchor from the solved
    //    world extent: right-anchor at the frame inset `W−26` (the corner-furniture
    //    convention, same as the retired 1414 = 1440−26) and seat the main baseline
    //    just ABOVE the SE scale-bar furniture — the scale bar baseline is `H−96`
    //    with a keep-out top at `H−120` (§1.7 furniturePlan), so `H−140` clears it
    //    by 20px; the feat sub-tallies stack UP from here (−14/line), further clear.
    //    These are EDGE-RELATIVE offsets (exactly what furniturePlan itself uses),
    //    not world literals → determinism (invariant 1) holds; emit rounds to 0.1. ──
    var r01 = function (v) { return Math.round(v * 10) / 10; };
    var tallyX = world ? r01(world.W - 26) : 1414;
    var tallyY = world ? r01(world.H - 140) : 862;
    // The tally + its sub-tallies live in their OWN group so the page can lift the whole
    // block above the decorative `.worldfill` grids (which paint over the in-the-paper sky
    // and would otherwise swallow a pointer) — the SAME relocation `.sky-hit` gets, so the
    // Survey button is reachable by a real click, not just by keyboard. Painted here in the
    // sky <g>; wireSkyCards re-parents it just below the interactive plan.
    var tallyLayer = svg('g', { 'class': 'sky-tally-layer' });
    var tally = svg('text', {
      x: tallyX, y: tallyY, 'text-anchor': 'end', 'class': 'sky-tally',
      id: 'sky-tally-main', role: 'button', tabindex: '0',
      'aria-label': 'The Survey of Heaven — ' + Sky.numberWord(charted) + ' of ' +
                    Sky.numberWord(wingTotal) + ' skies charted; open the sky index'
    });
    tally.textContent = 'Survey of Heaven — ' + charted + '/' + wingTotal + ' skies charted';
    tallyLayer.appendChild(tally);

    // ── the feat-group sub-tallies: each COMPLETED feat-group earns one right-anchored
    //    brass line, stacking UP from the main tally (tallyY) at -14px per line, tinted by
    //    its class. Data-driven off st.asterisms so adding a feat-group needs no edit
    //    here — only an entry in SUBTALLY. A line is emitted ONLY when genuinely
    //    complete (honest). Stack order follows FEATS array order:
    //      Optician (tallyY−14) · Automaton (−28) · Furnace (−42) … climbing the SE margin. ──
    var SUBTALLY = {
      feats:     { text: 'Feats of Light — the Optician charted',        cls: 'sky-tally-feats' },
      automaton: { text: "The Maker's Wing — the Automaton charted",     cls: 'sky-tally-automaton' },
      furnace:   { text: 'The Engine Room — the Furnace charted',        cls: 'sky-tally-furnace' },
      surveyor:  { text: 'Curved Country — the Surveyor charted',        cls: 'sky-tally-surveyor' },
      wagerer:   { text: 'The Belief Beam — the Wagerer charted',        cls: 'sky-tally-wagerer' },
      reckoner:  { text: 'The Reckoning Cabinet — the Reckoner charted',  cls: 'sky-tally-reckoner' },
      coilwright:{ text: 'Electromagnetism — the Coilwright charted',     cls: 'sky-tally-coilwright' },
      sirenist:  { text: 'Kinetics & Sound — the Sirenist charted',       cls: 'sky-tally-sirenist' }
    };
    var subY = r01(tallyY - 14);
    for (i = 0; i < FEATS.length; i++) {
      var fg = FEATS[i];
      var meta = SUBTALLY[fg.id];
      if (!meta) continue;
      var fast = null;
      for (j = 0; j < st.asterisms.length; j++) {
        if (st.asterisms[j].id === fg.id) { fast = st.asterisms[j]; break; }
      }
      if (!fast || !fast.complete) continue;             // honest: only when truly charted
      var ftally = svg('text', {
        x: tallyX, y: subY, 'text-anchor': 'end', 'class': 'sky-tally ' + meta.cls,
        'aria-hidden': 'true'
      });
      ftally.textContent = meta.text;
      tallyLayer.appendChild(ftally);
      subY -= 14;
    }
    g.appendChild(tallyLayer);

    // ── capstone: when ALL SIX WINGS are complete, set the firmament-survey flag once
    //    and add a faint all-skies glow band. This is the ORIGINAL capstone, unaffected
    //    by the feats constellation (allComplete is wings-only). ──
    if (st.allComplete) {
      if (lsGet(store, 'ws:flag:firmament-survey') == null) lsSet('ws:flag:firmament-survey', '1');
      g.classList.add('all-charted');
    }

    // insert as the FIRST child of #sheet (behind every painted layer)
    if (sheet.firstChild) sheet.insertBefore(g, sheet.firstChild);
    else sheet.appendChild(g);

    return g;
  };

  // browser global
  if (root && root.document) root.Sky = Sky;

  // dual-use module guard (forge strips exactly this braced single line)
  if (typeof module !== 'undefined' && module.exports) { module.exports = Sky; }
})(typeof globalThis !== 'undefined' ? globalThis : this);
