#!/usr/bin/env node
/* ═══════════════════════════════════════════════════════════════════════════
   sky.test.cjs — Node self-test for tools/sky/sky.js (the workshop's "a self-test
   proves it" promise). Run:  node tools/sky/sky.test.cjs

   No deps. Requires the UNSTRIPPED module headlessly (it exports `Sky` via the
   CommonJS guard) and asserts the five load-bearing properties of the pure core:

     (1) DETERMINISM + ORDER-INDEPENDENCE — state() of the same visit-set is byte
         stable, and is identical no matter the order the ids were visited.
     (2) MONOTONICITY — a SUPERSET of visits ⇒ a SUPERSET of lit stars / line
         points / completed asterisms (a feature, once on, is never removed).
     (3) COMPLETION-IFF — for every asterism, complete === members.every(visited),
         swept over a battery including each member-minus-one (NO false completion)
         and the full set; allComplete <=> the capstone condition.
     (4) CATALOG INTEGRITY — every star position lies INSIDE the 1440×900 viewBox
         AND OUTSIDE every footprint bbox, the plan furniture, and the manor pool.
     (5) BIJECTION — every front-door PLACES id maps to exactly one catalog star;
         every wing member is a unique catalog id belonging to exactly one wing
         (no orphan, no dupe).

   Prints "sky self-test: N/N PASS"; exits non-zero on any failure.
   ═══════════════════════════════════════════════════════════════════════════ */
'use strict';

const Sky = require('./sky.js');
const CATALOG = Sky.CATALOG;
const WINGS = Sky.WINGS;
// Sky.FEATS is now an ARRAY of feat-GROUPS (each a BONUS asterism — drawn + named like a
// wing, but NONE ever gates the all-skies capstone). Tolerate the legacy single-object
// shape so this battery is robust either way.
const FEAT_GROUPS = Array.isArray(Sky.FEATS) ? Sky.FEATS : [Sky.FEATS];
const OPTICIAN  = FEAT_GROUPS.find(g => g.id === 'feats');     // the Hall's nine Feats of Light
const AUTOMATON = FEAT_GROUPS.find(g => g.id === 'automaton'); // Clockwork's 4 bench crumbs
const FURNACE   = FEAT_GROUPS.find(g => g.id === 'furnace');   // the Engine Room's 4 bench crumbs
const SURVEYOR  = FEAT_GROUPS.find(g => g.id === 'surveyor');  // Curved Country's founding star (The Holonomy Walk)
const PILOT     = FEAT_GROUPS.find(g => g.id === 'pilot');     // Optics' fly-through founding star (The Photon's Errand)
// the legacy Optician sub-suite (174-228) refers to `FEATS` as the single Optician group.
const FEATS = OPTICIAN;

/* ── tiny assert harness ──────────────────────────────────────────────────── */
let pass = 0, fail = 0;
function ok(cond, label) {
  if (cond) { pass++; }
  else { fail++; console.error('  ✗ FAIL: ' + label); }
}
function eq(a, b, label) {
  ok(a === b, label + ' (got ' + JSON.stringify(a) + ', want ' + JSON.stringify(b) + ')');
}

/* ── geometry: the front-door footprint bboxes + plan furniture + manor pool ──
   Mirrors index.src.html's PLACES footprints (footBBox) and FURNITURE, plus the
   manor candle-pool rect. A star must lie inside the viewBox and outside all. */
const VIEWBOX = { x: 0, y: 0, w: 1440, h: 900 };
/* The footprint bboxes are now GENERATED by the Layout engine (tools/layout) from
   the declarative PLACES (district + tier + wing). This mirror is emitted by
   `node tools/layout/emit-mirror.cjs` and updated in LOCKSTEP whenever a room's
   declaration changes — keep it in sync or this test false-fails. Every generated
   box is verified star-clear (all 35 catalog stars lie outside the interior FIELD). */
const FOOTPRINTS = [
  { id: 'verse',            x: 683,   y: 358,  w: 29,   h: 21 },
  { id: 'compositor',       x: 715,   y: 358,  w: 29,   h: 21 },
  { id: 'cartographer',     x: 683,   y: 382,  w: 29,   h: 21 },
  { id: 'sound-garden',     x: 683,   y: 410,  w: 29,   h: 21 },
  { id: 'threshold',        x: 715,   y: 410,  w: 29,   h: 21 },
  { id: 'strange-garden',   x: 322,   y: 629,  w: 67,   h: 47 },
  { id: 'firmament',        x: 288,   y: 194,  w: 24,   h: 24 },  // tower r→bbox
  { id: 'daedalus',         x: 1017,  y: 410,  w: 67,   h: 46 },
  { id: 'arcade',           x: 1017,  y: 304,  w: 67,   h: 46 },
  { id: 'workbench',        x: 520,   y: 589,  w: 88,   h: 61 },
  { id: 'undercroft',       x: 698,   y: 517,  w: 46,   h: 64 },
  { id: 'hall-of-mirrors',  x: 275,   y: 404,  w: 73,   h: 50 },  // the optics wing — the feat-stars cluster beside it
  { id: 'refraction-run',   x: 275,   y: 461,  w: 73,   h: 50 },  // The Photon's Errand — the optics fly-through, the new 'tank' footprint below the Hall
  { id: 'gnomon',           x: 1118,  y: 203,  w: 142,  h: 98 }  // The Hours — the horology wing's open east-park sundial
];
const FURNITURE = [
  { id: 'compass',      x: 74,   y: 82,  w: 92,  h: 92 },
  { id: 'scalebar',     x: 1086, y: 798, w: 212, h: 52 },
  { id: 'nameplate',    x: 96,   y: 760, w: 266, h: 78 }  // the demoted corner survey nameplate
  // the two old floating zone-label boxes are GONE — zone labels now sit ON district
  // boundaries (renderer-drawn), so they are no longer hand-tuned furniture obstacles.
];
const MANOR_POOL = { id: 'manor-pool', x: 421, y: 150, w: 600, h: 600 };
/* a star is drawn as a tiny disc; we clear every obstacle by this half-extent so
   a kindled star never touches a footprint/furniture edge. */
const STAR_PAD = 12;

/* the front-door PLACES ids (the visible POIs + the gated cellar stair) — must
   each map to exactly one catalog star (the BIJECTION half that ties to the map). */
const PLACES_IDS = [
  'verse', 'compositor', 'cartographer', 'sound-garden', 'threshold',
  'strange-garden', 'firmament', 'daedalus', 'arcade', 'workbench', 'undercroft', 'gnomon'
];

function boxHit(s, b) {
  return s.x + STAR_PAD > b.x && s.x - STAR_PAD < b.x + b.w &&
         s.y + STAR_PAD > b.y && s.y - STAR_PAD < b.y + b.h;
}
function inViewBox(s) {
  return s.x - STAR_PAD >= VIEWBOX.x && s.y - STAR_PAD >= VIEWBOX.y &&
         s.x + STAR_PAD <= VIEWBOX.x + VIEWBOX.w && s.y + STAR_PAD <= VIEWBOX.y + VIEWBOX.h;
}

/* ── (1) DETERMINISM + ORDER-INDEPENDENCE ─────────────────────────────────── */
(function () {
  const A = ['verse', 'scriptorium', 'firmament', 'daedalus'];
  const B = A.slice().reverse();                 // same set, opposite order
  const sA = Sky.state(A, CATALOG, WINGS);
  const sB = Sky.state(B, CATALOG, WINGS);
  eq(JSON.stringify(sA), JSON.stringify(sB), 'state() is order-independent for the same set');
  // a Set and an array of the same ids give the same result
  const sSet = Sky.state(new Set(A), CATALOG, WINGS);
  eq(JSON.stringify(sA), JSON.stringify(sSet), 'state() treats a Set and an array identically');
  // determinism: repeated calls byte-stable
  eq(JSON.stringify(Sky.state(A, CATALOG, WINGS)), JSON.stringify(sA), 'state() is deterministic across calls');
})();

/* ── (2) MONOTONICITY — superset of visits ⇒ superset of every feature ──────── */
(function () {
  const allIds = Object.keys(CATALOG);
  // a chain of growing subsets
  const chain = [
    [],
    ['firmament'],
    ['firmament', 'orrery'],
    ['firmament', 'orrery', 'verse'],
    ['firmament', 'orrery', 'verse', 'scriptorium'],
    ['firmament', 'orrery', 'verse', 'scriptorium', 'daedalus', 'ariadne'],
    allIds.slice()
  ];
  let monoOK = true, compMonoOK = true, ptMonoOK = true;
  for (let k = 1; k < chain.length; k++) {
    const prev = Sky.state(chain[k - 1], CATALOG, WINGS);
    const cur = Sky.state(chain[k], CATALOG, WINGS);
    // lit stars: every star lit before stays lit
    const curStarIds = new Set(cur.stars.map(s => s.id));
    prev.stars.forEach(s => { if (!curStarIds.has(s.id)) monoOK = false; });
    // completed asterisms: every wing complete before stays complete
    const curComplete = new Set(cur.asterisms.filter(a => a.complete).map(a => a.id));
    prev.asterisms.filter(a => a.complete).forEach(a => { if (!curComplete.has(a.id)) compMonoOK = false; });
    // line points: each wing's drawn point-count never decreases
    const ptCount = (st) => { const m = {}; st.lines.forEach(l => { m[l.wing] = l.points.length; }); return m; };
    const pp = ptCount(prev), cp = ptCount(cur);
    for (const wid in pp) { if ((cp[wid] || 0) < pp[wid]) ptMonoOK = false; }
  }
  ok(monoOK, 'MONOTONICITY: a superset of visits never removes a lit star');
  ok(compMonoOK, 'MONOTONICITY: a superset of visits never un-completes an asterism');
  ok(ptMonoOK, 'MONOTONICITY: a superset of visits never shrinks a wing line');
})();

/* ── (3) COMPLETION-IFF — complete === members.every(visited); battery sweep ──
   Pass the FULL feat-group ARRAY (the Optician + the Automaton + the Furnace) so the
   battery exercises every group exactly as the renderer's default does. ── */
(function () {
  // full set: every asterism (wings AND every feat-group) complete, capstone on
  const full = Object.keys(CATALOG);
  const sFull = Sky.state(full, CATALOG, WINGS, FEAT_GROUPS);
  let allComp = true;
  sFull.asterisms.forEach(a => { if (!a.complete) allComp = false; });
  ok(allComp, 'COMPLETION: full visit-set completes every asterism (incl. all five feat-groups)');
  eq(sFull.allComplete, true, 'COMPLETION: allComplete true on the full set (capstone)');

  // empty set: nothing complete, allComplete false
  const sEmpty = Sky.state([], CATALOG, WINGS, FEAT_GROUPS);
  ok(sEmpty.asterisms.every(a => !a.complete), 'COMPLETION: empty set completes nothing');
  eq(sEmpty.allComplete, false, 'COMPLETION: allComplete false on the empty set');

  // member-minus-one: for EACH wing, drop ONE member from the full set → that
  // wing (and only that wing) must be incomplete; allComplete must be false.
  const allGroups = WINGS.concat(FEAT_GROUPS);
  let iffOK = true, noFalseComplete = true;
  for (const wing of WINGS) {
    for (const drop of wing.members) {
      const visited = full.filter(id => id !== drop);
      const st = Sky.state(visited, CATALOG, WINGS, FEAT_GROUPS);
      const target = st.asterisms.find(a => a.id === wing.id);
      if (target.complete) noFalseComplete = false;     // missing a member ⇒ must NOT complete
      if (st.allComplete) iffOK = false;                 // a hole ⇒ capstone must NOT fire
      // and the IFF must hold for EVERY asterism in this state (wings + every feat-group)
      st.asterisms.forEach(a => {
        const g = allGroups.find(x => x.id === a.id);
        const everVisited = g.members.every(m => visited.indexOf(m) >= 0);
        if (a.complete !== everVisited) iffOK = false;
      });
    }
  }
  ok(noFalseComplete, 'COMPLETION-IFF: dropping any one member un-completes that wing (no false completion)');
  ok(iffOK, 'COMPLETION-IFF: complete === members.every(visited) across the member-minus-one battery');
  eq(sFull.allComplete, WINGS.every(w => w.members.every(m => full.indexOf(m) >= 0)),
     'COMPLETION-IFF: allComplete <=> every wing complete');
})();

/* ── (3b) THE FEATS CONSTELLATION IS A BONUS — it draws/names/completes like a wing
   but is ADDITIVE: it NEVER gates the all-skies capstone (allComplete = the six
   companion-wings only). Its completion is keyed off the earned-flag pseudo-ids. ── */
(function () {
  const featIds = FEATS.members.slice();              // the 9 feat-<X> pseudo-ids
  const wingIds = [];
  WINGS.forEach(w => w.members.forEach(m => wingIds.push(m)));

  // (a) all six wings complete but ZERO feats → capstone fires, feats incomplete.
  const sWingsOnly = Sky.state(wingIds, CATALOG, WINGS, FEATS);
  eq(sWingsOnly.allComplete, true, 'FEATS: completing the six wings fires the capstone with NO feats earned');
  const featAstWO = sWingsOnly.asterisms.find(a => a.id === FEATS.id);
  ok(featAstWO && !featAstWO.complete, 'FEATS: with no feats earned the feats constellation is incomplete');

  // (b) all nine feats earned but NO wings → feats complete, capstone does NOT fire.
  const sFeatsOnly = Sky.state(featIds, CATALOG, WINGS, FEATS);
  eq(sFeatsOnly.allComplete, false, 'FEATS: completing the feats constellation does NOT fire the capstone');
  const featAstFO = sFeatsOnly.asterisms.find(a => a.id === FEATS.id);
  ok(featAstFO && featAstFO.complete, 'FEATS: all nine feats earned ⇒ the feats constellation completes');
  ok(featIds.every(id => sFeatsOnly.stars.some(s => s.id === id)),
     'FEATS: all nine feat-stars kindle when their flags are earned');

  // (c) completion-iff for the feats group: dropping ANY one feat un-completes it,
  //     and never touches the (still-false) capstone.
  let featIffOK = true;
  for (const drop of featIds) {
    const visited = featIds.filter(id => id !== drop);
    const st = Sky.state(visited, CATALOG, WINGS, FEATS);
    const fa = st.asterisms.find(a => a.id === FEATS.id);
    if (fa.complete) featIffOK = false;                 // missing one feat ⇒ must NOT complete
    if (st.allComplete) featIffOK = false;              // feats never gate the capstone
  }
  ok(featIffOK, 'FEATS-IFF: dropping any one of the nine feats un-completes the constellation (no false completion)');

  // (d) the partial-kindle path: a SUBSET of feats lights only those stars, draws a
  //     partial (incomplete) line, and never completes.
  const someFeats = featIds.slice(0, 4);
  const sPartial = Sky.state(someFeats, CATALOG, WINGS, FEATS);
  ok(someFeats.every(id => sPartial.stars.some(s => s.id === id)), 'FEATS: a subset of feats kindles exactly those stars');
  ok(!featIds.slice(4).some(id => sPartial.stars.some(s => s.id === id)), 'FEATS: unearned feats stay dark');
  const fline = sPartial.lines.find(l => l.wing === FEATS.id);
  ok(fline && fline.complete === false, 'FEATS: a partial feats set draws an INCOMPLETE line');

  // (e) visitedFromStore maps ws:flag:earned-<X> → feat-<X> and keeps ws:seen rooms.
  const fakeStore = { ok: true, all: {
    'ws:seen:firmament': '1', 'ws:seen:orrery': '1',
    'ws:flag:earned-rainbow': '1', 'ws:flag:earned-maze': '1',
    'ws:flag:sky-bootstrap': '1'   // a non-earned, non-seen flag must be IGNORED
  } };
  const v = Sky.visitedFromStore(fakeStore);
  ok(v['firmament'] && v['orrery'], 'visitedFromStore: ws:seen rooms still map (regression)');
  ok(v['feat-rainbow'] && v['feat-maze'], 'visitedFromStore: ws:flag:earned-<X> ⇒ feat-<X> visited');
  ok(!v['feat-halo'], 'visitedFromStore: an un-earned feat is NOT visited');
  ok(!v['sky-bootstrap'] && !v['feat-bootstrap'], 'visitedFromStore: unrelated flags are ignored');
})();

/* ── the WINGS-ONLY capstone predicate. allComplete MUST equal exactly this — the
   feat-groups (Optician/Automaton/Furnace) are ADDITIVE and can never move it. ── */
function capstoneShouldBe(visited) {
  const vs = Array.isArray(visited) ? new Set(visited) : visited;
  const has = id => (vs.has ? vs.has(id) : !!vs[id]);
  return WINGS.length > 0 && WINGS.every(w => w.members.every(m => has(m)));
}
const ALL_WING_MEMBERS = [];
WINGS.forEach(w => w.members.forEach(m => ALL_WING_MEMBERS.push(m)));

/* ── (3c) THE TWO NEW REWARD-WING ASTERISMS (the Automaton + the Furnace) ─────────
   Each is a bonus feat-group built on PLAIN room ids (the wing's bench crumbs), drawn
   + named like a wing but NEVER feeding the capstone. For each: it EXISTS, has exactly
   four members, every member is a catalog id, carries a non-empty name + myth, matches
   the EXACT member SET (order-free), completes only on the full set, and completing it
   leaves the wings-only capstone untouched. ── */
[AUTOMATON, FURNACE].forEach(GRP => {
  const NAME = GRP ? GRP.id : '(missing)';
  ok(!!GRP, 'NEWGRP ' + NAME + ': the feat-group exists in Sky.FEATS');
  if (!GRP) return;
  eq(GRP.members.length, 4, 'NEWGRP ' + NAME + ': has exactly four members');
  ok(GRP.members.every(m => !!CATALOG[m]), 'NEWGRP ' + NAME + ': every member is a catalog id');
  ok(typeof GRP.name === 'string' && GRP.name.length > 0
     && typeof GRP.myth === 'string' && GRP.myth.length > 0,
     'NEWGRP ' + NAME + ': carries a non-empty name + myth');

  // EXACT member set (sorted compare so polyline order is not brittle)
  const expected = { automaton: ['context-window','partition','temperature-dial','the-turn'],
                     furnace:   ['brownian','carnot','demon','stirling'] }[GRP.id];
  eq(JSON.stringify(GRP.members.slice().sort()), JSON.stringify(expected),
     'NEWGRP ' + NAME + ': the EXACT member set matches (order-free)');

  // group-only completes but NEVER fires the capstone (no wings visited)
  const sGrp = Sky.state(GRP.members, CATALOG, WINGS, FEAT_GROUPS);
  const ast = sGrp.asterisms.find(a => a.id === GRP.id);
  ok(ast && ast.complete, 'NEWGRP ' + NAME + ': its four crumbs complete the asterism');
  eq(sGrp.allComplete, false, 'NEWGRP ' + NAME + ': completing it NEVER fires the wings-only capstone');
  eq(sGrp.allComplete, capstoneShouldBe(GRP.members),
     'NEWGRP ' + NAME + ': allComplete == the wings-only predicate (group-only)');

  // CAPSTONE-BYTE-INVARIANCE: six wings + ZERO new crumbs ⇒ capstone TRUE & group incomplete
  const sWingsNoGrp = Sky.state(ALL_WING_MEMBERS, CATALOG, WINGS, FEAT_GROUPS);
  eq(sWingsNoGrp.allComplete, true, 'NEWGRP ' + NAME + ': six wings + zero new crumbs ⇒ capstone TRUE');
  const astWO = sWingsNoGrp.asterisms.find(a => a.id === GRP.id);
  ok(astWO && !astWO.complete, 'NEWGRP ' + NAME + ': with no crumbs the group is incomplete (capstone stands alone)');

  // completion-IFF drop-one sweep: dropping ANY one of the group's crumbs un-completes
  // it, leaves allComplete == the wings-only predicate, and never touches the OTHER
  // feat-groups (the Optician + the sibling new group).
  const OTHERS = FEAT_GROUPS.filter(g => g.id !== GRP.id);
  let dropOK = true, siblingsUntouched = true;
  for (const drop of GRP.members) {
    const visited = ALL_WING_MEMBERS.concat(GRP.members).filter(id => id !== drop);
    const st = Sky.state(visited, CATALOG, WINGS, FEAT_GROUPS);
    const t = st.asterisms.find(a => a.id === GRP.id);
    if (t.complete) dropOK = false;                       // missing one crumb ⇒ NOT complete
    if (st.allComplete !== capstoneShouldBe(visited)) dropOK = false;
    if (st.allComplete !== true) dropOK = false;          // the six wings are all present ⇒ TRUE
    OTHERS.forEach(o => {
      const oa = st.asterisms.find(a => a.id === o.id);
      const should = o.members.every(m => visited.indexOf(m) >= 0);
      if (oa.complete !== should) siblingsUntouched = false;
    });
  }
  ok(dropOK, 'NEWGRP ' + NAME + ': drop-one un-completes it; allComplete == wings-only predicate (stays TRUE)');
  ok(siblingsUntouched, 'NEWGRP ' + NAME + ': dropping a crumb never touches the OTHER feat-groups');
});

/* ── (A5) THE GLOBAL CAPSTONE SWEEP — allComplete is byte-invariant: wings-only.
   Full catalog ⇒ TRUE; drop each WING member ⇒ FALSE and == predicate; drop each NEW
   crumb ⇒ stays TRUE; empty ⇒ FALSE. One named ok. ── */
(function () {
  const full = Object.keys(CATALOG);
  let capInvariant = true;
  const check = (visited, why) => {
    const got = Sky.state(visited, CATALOG, WINGS, FEAT_GROUPS).allComplete;
    const want = capstoneShouldBe(visited);
    if (got !== want) { capInvariant = false; console.error('    · capstone drift (' + why + '): got ' + got + ' want ' + want); }
    return got;
  };
  // full catalog ⇒ TRUE
  if (check(full, 'full') !== true) capInvariant = false;
  // empty ⇒ FALSE
  if (check([], 'empty') !== false) capInvariant = false;
  // drop each WING member ⇒ FALSE (and == predicate)
  for (const m of ALL_WING_MEMBERS) {
    if (check(full.filter(id => id !== m), 'drop wing ' + m) !== false) capInvariant = false;
  }
  // drop each NEW crumb (Automaton + Furnace members) ⇒ stays TRUE (wings still whole)
  const NEW_CRUMBS = [].concat(AUTOMATON.members, FURNACE.members);
  for (const m of NEW_CRUMBS) {
    if (check(full.filter(id => id !== m), 'drop crumb ' + m) !== true) capInvariant = false;
  }
  // drop each OPTICIAN feat ⇒ stays TRUE (the Optician never gated the capstone either)
  for (const m of OPTICIAN.members) {
    if (check(full.filter(id => id !== m), 'drop optician ' + m) !== true) capInvariant = false;
  }
  ok(capInvariant, 'CAPSTONE BYTE-INVARIANCE: allComplete == the wings-only predicate across full/empty/drop-wing/drop-crumb/drop-feat');
})();

/* ── (4) CATALOG INTEGRITY — every star inside the viewBox & outside obstacles ── */
(function () {
  let inOK = true, clearOK = true;
  for (const id in CATALOG) {
    const c = CATALOG[id];
    const s = { x: c.x, y: c.y };
    if (!inViewBox(s)) { inOK = false; console.error('    · ' + id + ' out of bounds at (' + c.x + ',' + c.y + ')'); }
    for (const f of FOOTPRINTS) if (boxHit(s, f)) { clearOK = false; console.error('    · ' + id + ' over footprint ' + f.id); }
    for (const f of FURNITURE) if (boxHit(s, f)) { clearOK = false; console.error('    · ' + id + ' over furniture ' + f.id); }
    if (boxHit(s, MANOR_POOL)) { clearOK = false; console.error('    · ' + id + ' inside the manor candle-pool'); }
    // a magnitude is present and sane
    if (!(c.mag >= 1 && c.mag <= 3)) clearOK = false;
  }
  ok(inOK, 'CATALOG INTEGRITY: every star lies inside the 1440×900 viewBox');
  ok(clearOK, 'CATALOG INTEGRITY: every star clears every footprint, furniture box, and the manor pool');

  // ── star-vs-star clearance: no two stars sit within 2*STAR_PAD on BOTH axes (so a
  //    kindled disc never touches another). This is the genuinely-missing assertion —
  //    the per-id integrity loop covers stars-vs-bboxes, this covers stars-vs-stars. ──
  const ids = Object.keys(CATALOG);
  let starClearOK = true;
  for (let a = 0; a < ids.length; a++) {
    for (let b = a + 1; b < ids.length; b++) {
      const ca = CATALOG[ids[a]], cb = CATALOG[ids[b]];
      if (Math.abs(ca.x - cb.x) < 2 * STAR_PAD && Math.abs(ca.y - cb.y) < 2 * STAR_PAD) {
        starClearOK = false;
        console.error('    · ' + ids[a] + ' overlaps ' + ids[b] +
          ' (Δx=' + Math.abs(ca.x - cb.x) + ', Δy=' + Math.abs(ca.y - cb.y) + ')');
      }
    }
  }
  ok(starClearOK, 'CATALOG INTEGRITY: no two stars are within 2*STAR_PAD on both axes (star-vs-star clearance)');
})();

/* ── (5) BIJECTION — PLACES↔catalog + wing membership exactly-once ──────────── */
(function () {
  const catIds = Object.keys(CATALOG);
  // catalog has no duplicate keys by construction; verify count == distinct
  eq(catIds.length, new Set(catIds).size, 'BIJECTION: catalog ids are unique (no dupe star)');

  // every front-door PLACES id maps to exactly one catalog star
  let placesOK = true;
  for (const pid of PLACES_IDS) {
    if (!CATALOG[pid]) { placesOK = false; console.error('    · PLACES id "' + pid + '" has NO catalog star'); }
  }
  ok(placesOK, 'BIJECTION: every front-door PLACES id maps to exactly one catalog star');

  // every wing member is a valid catalog id (no orphan) and belongs to exactly one wing (no dupe)
  const memberWing = {};
  let orphanOK = true, oneWingOK = true;
  for (const wing of WINGS) {
    for (const m of wing.members) {
      if (!CATALOG[m]) { orphanOK = false; console.error('    · wing "' + wing.id + '" member "' + m + '" is not a catalog id'); }
      if (memberWing[m] != null) { oneWingOK = false; console.error('    · "' + m + '" is in two wings: ' + memberWing[m] + ' & ' + wing.id); }
      memberWing[m] = wing.id;
    }
  }
  ok(orphanOK, 'BIJECTION: every wing member is a valid catalog id (no orphan)');
  ok(oneWingOK, 'BIJECTION: every wing member belongs to exactly one wing (no dupe)');

  // every wing-member PLACES id is in exactly one wing (the tie that makes the
  // map↔asterism mapping unambiguous for the rooms that DO belong to a wing)
  let placesWingOK = true;
  for (const pid of PLACES_IDS) {
    if (CATALOG[pid] && WINGS.some(w => w.members.indexOf(pid) >= 0)) {
      const wingsWith = WINGS.filter(w => w.members.indexOf(pid) >= 0);
      if (wingsWith.length !== 1) { placesWingOK = false; console.error('    · PLACES wing-member "' + pid + '" is in ' + wingsWith.length + ' wings'); }
    }
  }
  ok(placesWingOK, 'BIJECTION: every wing-member front-door id belongs to exactly one wing');

  // exactly six wings, each a pair (the companion-pair structure the mission fixes)
  eq(WINGS.length, 6, 'BIJECTION: there are exactly six wings');
  ok(WINGS.every(w => w.members.length === 2), 'BIJECTION: every wing is a companion-pair (2 members)');

  // ── the feat-GROUPS: a group-agnostic disjointness sweep (replaces the old
  //    `feat-`-prefix-hardcoded block, which would FALSE-FAIL on plain room-id members).
  //    There are exactly five feat-groups with distinct ids; EVERY member belongs to
  //    exactly one group across WINGS + FEAT_GROUPS (no dupe); each plain-room-id NEW-group
  //    member is a valid catalog id (NOT feat-). The `feat-` prefix assertion is kept,
  //    scoped to the OPTICIAN only. The Surveyor (Curved Country) and The Pilot (Optics'
  //    fly-through) are each founded on a real front-door room's `ws:seen` crumb, sized to
  //    grow as their wings' siblings ship. ──
  eq(FEAT_GROUPS.length, 5, 'BIJECTION: there are exactly five feat-groups');
  eq(FEAT_GROUPS.length, new Set(FEAT_GROUPS.map(g => g.id)).size, 'BIJECTION: the five feat-group ids are distinct');
  ok(!!OPTICIAN && !!AUTOMATON && !!FURNACE && !!SURVEYOR && !!PILOT, 'BIJECTION: the five feat-groups are Optician + Automaton + Furnace + Surveyor + Pilot');

  // every member belongs to exactly one group across WINGS + FEAT_GROUPS (no dupe across
  // the whole catalog of asterisms). memberWing already holds the wing assignments.
  const memberGroup = {};            // id → group id (wings + feat-groups)
  let oneGroupOK = true;
  for (const wing of WINGS) for (const m of wing.members) memberGroup[m] = wing.id;
  for (const grp of FEAT_GROUPS) {
    for (const m of grp.members) {
      if (memberGroup[m] != null) { oneGroupOK = false; console.error('    · "' + m + '" is in two groups: ' + memberGroup[m] + ' & ' + grp.id); }
      memberGroup[m] = grp.id;
    }
  }
  ok(oneGroupOK, 'BIJECTION: every member belongs to exactly one group across WINGS + FEAT_GROUPS (no dupe)');

  // each feat-group carries name + myth + distinct, all-catalog members
  let grpShapeOK = true;
  for (const grp of FEAT_GROUPS) {
    if (!(typeof grp.id === 'string' && grp.id.length > 0
          && typeof grp.name === 'string' && grp.name.length > 0
          && typeof grp.myth === 'string' && grp.myth.length > 0)) {
      grpShapeOK = false; console.error('    · feat-group "' + grp.id + '" missing id/name/myth');
    }
    if (grp.members.length !== new Set(grp.members).size) { grpShapeOK = false; console.error('    · feat-group "' + grp.id + '" has duplicate members'); }
    if (!grp.members.every(m => !!CATALOG[m])) { grpShapeOK = false; console.error('    · feat-group "' + grp.id + '" has a non-catalog member'); }
  }
  ok(grpShapeOK, 'BIJECTION: every feat-group carries id/name/myth + distinct, all-catalog members');

  // the OPTICIAN keeps its nine feat-<X> pseudo-id contract (prefix scoped HERE only)
  eq(OPTICIAN.members.length, 9, 'BIJECTION: the Optician has exactly nine members');
  ok(OPTICIAN.members.every(m => m.indexOf('feat-') === 0),
     'BIJECTION: every Optician member carries the feat- prefix (pseudo-id)');
  ok(OPTICIAN.members.every(m => PLACES_IDS.indexOf(m) < 0),
     'BIJECTION: no Optician pseudo-id collides with a front-door PLACES id');

  // each NEW-group member is a PLAIN room id (NOT feat-), a valid catalog id, NOT a PLACES_ID
  let newPlainOK = true, newCatOK = true, newNotPlacesOK = true;
  for (const grp of [AUTOMATON, FURNACE]) {
    for (const m of grp.members) {
      if (m.indexOf('feat-') === 0) { newPlainOK = false; console.error('    · new-group member "' + m + '" wrongly carries the feat- prefix'); }
      if (!CATALOG[m]) { newCatOK = false; console.error('    · new-group member "' + m + '" is not a catalog id'); }
      if (PLACES_IDS.indexOf(m) >= 0) { newNotPlacesOK = false; console.error('    · new-group member "' + m + '" collides with a PLACES id'); }
    }
  }
  ok(newPlainOK, 'BIJECTION: every Automaton/Furnace member is a PLAIN room id (no feat- prefix)');
  ok(newCatOK, 'BIJECTION: every Automaton/Furnace member is a valid catalog id');
  ok(newNotPlacesOK, 'BIJECTION: no Automaton/Furnace member collides with a front-door PLACES id');

  // still exactly six wings, each a pair (regression — re-asserted after the reshape)
  eq(WINGS.length, 6, 'BIJECTION: still exactly six wings after the reshape');
})();

/* ── report ─────────────────────────────────────────────────────────────────── */
const total = pass + fail;
if (fail) {
  console.error('\nsky self-test: ' + pass + '/' + total + ' PASS — ' + fail + ' FAILED');
  process.exit(1);
}
console.log('sky self-test: ' + pass + '/' + total + ' PASS');
process.exit(0);
